### ISSUE TITLE
GPSPRINGSECURITYCORE-300: @Secured not working for namespaced controllers with same name

### ISSUE THREAD

**Issue by graemerocher** [grails-plugins/grails-spring-security-core#102]
Original Reporter: flextron
Environment: grails-2.4.2, spring-security-core:2.0-RC4
Version: Not Specified
Migrated From: http://jira.grails.org/browse/GPSPRINGSECURITYCORE-300

I have 2 DashboardController. However both take annotation of the controller without the namespace.

The first can't be redirected to login. I tried using the annotation permitAll unsuccessfully.

`DashboardController.groovy(with namespace)`:

```
class DashboardController {

    static namespace = 'XXX'

}
```

`DashboardController.groovy (without namespace)`:

```
@Secured('IS_AUTHENTICATED_FULLY')
class DashboardController {
}
```

**Comment by alvarosanchez** [comment]
This already works. See https://github.com/grails-plugins/grails-spring-security-core/blob/2.x/functional-test-app/test/functional/NamespaceSecuritySpec.groovy#L116:L130
