### ISSUE TITLE
GPSPRINGSECURITYCORE-286: @Secured annotation inheritance doesn't work

### ISSUE THREAD

**Issue by graemerocher** [grails-plugins/grails-spring-security-core#106]
Original Reporter: niko.makela
Environment: Not Specified
Version: Not Specified
Migrated From: http://jira.grails.org/browse/GPSPRINGSECURITYCORE-286

{quote}
I'm using Grails 2.2.4 / 2.3.7 with Sprint Security Core 1.2.7.3. When extending a controller, rules added to a base controller with @secured annotation are not affecting in extending controller. 

{code:title=BaseController}
@Secured(['ROLE_USER', 'ROLE_ADMIN', 'ROLE_SUPERUSER'])
class BaseController {
    static allowedMethods = [save: "POST", update: "POST", delete: "POST"]

```
@Secured(['ROLE_ADMIN', 'ROLE_SUPERUSER'])
def delete(Long id) {
    withForm{
```

{code}

{code:title=ExtendingController}
class ExtendingController extends BaseController {

```
//My workaround
@Secured(['ROLE_ADMIN', 'ROLE_SUPERUSER'])
def delete(Long id) {
    super.delete(id)
}
```

{code}
{quote}

**Comment by VitaliiH** [comment]
The bug is still reproducing. Used: grails 2.3.5, spring-security-core:2.0-SNAPSHOT version of plugin. Tried spring-security-core:2.0-RC5 as well.
