### ISSUE TITLE
GPSPRINGSECURITYCORE-163: Role hierarchy configuration to database

### ISSUE THREAD

**Issue by graemerocher** [grails-plugins/grails-spring-security-core#122]
Original Reporter: smakela
Environment: Not Specified
Version: Not Specified
Migrated From: http://jira.grails.org/browse/GPSPRINGSECURITYCORE-163

Configuring role hierarchy in the database should be option to this feature.
Hierarchical roles are now configured in the Config.groovy.

Multitenancy for the role hierarchy would be a nice option.
So client A and B could have different role hierarchies.

**Comment by burtbeckwith** [comment]
Fixed by https://github.com/grails-plugins/grails-spring-security-core/commit/67c2fa4ce9c4abe71e0838dc563cafa3a1be9093
