### ISSUE TITLE
GPSPRINGSECURITYCORE-210: existing grails.plugins.springsecurity.filterChain.chainMap ignored in SpringSecurityUtils.clientRegisterFilter

### ISSUE THREAD

**Issue by graemerocher** [grails-plugins/grails-spring-security-core#138]
Original Reporter: ibrahimovic
Environment: Windows 7, Grails 2.1
Version: Not Specified
Migrated From: http://jira.grails.org/browse/GPSPRINGSECURITYCORE-210

All filters declared in grails.plugins.springsecurity.filterChain.filterNames
are executed on all url declared in grails.plugins.springsecurity.filterChain.chainMap even if I use the negative syntax (JOINED_FILTERS,-exceptionTranslationFilter). 
This issue occurs when I use in bootstrap the following statement : SpringSecurityUtils.clientRegisterFilter(...).

When I comment the previous statement in Bootstrap, filters are correctly ignored in chainMap with negative syntax.

**Comment by volnei** [comment]
This bug still occurs, can someone reopen this?

**Comment by thagul** [comment]
It occurs also in 2.0-RC5

**Comment by volnei** [comment]
I think this an important fix to 3.0 GA, is it possible?

**Comment by burtbeckwith** [comment]
Yes, I'm planning on including this in the M3 release

**Comment by volnei** [comment]
Thanks @burtbeckwith

**Comment by burtbeckwith** [comment]
This is fixed and will be in 3.0.0.M3.

Spring Boot auto-registers all filters that it finds in the ApplicationContext, so to prevent the filter from being applied to all requests, you need to create a `FilterRegistrationBean` with `enabled` set to `false`, e.g.

    import com.mycompany.myapp.MyFilter
    import org.springframework.boot.context.embedded.FilterRegistrationBean

    beans = {
       myFilter(MyFilter) {
          // properties
       }

       myFilterDeregistrationBean(FilterRegistrationBean) {
          filter = ref('myFilter')
          enabled = false
       }
    }

**Comment by volnei** [comment]
Burt, this is only part of the problem I had solved. The most important part is that when we register a filter with SpringSecurityUtils.clientRegisterFilter this is not removed when you use the config with chainMap as explained here 

https://github.com/grails-plugins/grails-spring-security-core/issues/138#issuecomment-155484542

It is solved as well?

Thanks

**Comment by burtbeckwith** [comment]
Sorry, I wasn't clear. The issue is fixed, but when I was testing it I was still seeing log statements from my test filter for all requests, and that was due to Boot autoregistering the filter a second time in addition to the one I registered in the filter chain. The fix is in commit f85ce9ae1b46e2a0ac96d6320c13e60f1c1499f9

**Comment by volnei** [comment]
Great! Thanks! :smiley:

**Comment by kossatzd** [comment]
I'm facing another issue related to this.  Let me know if I'm wrong or if I should create another issue.

I have a chainMap like:
`pattern: '/assets/**',      filters: 'none'`

And when I register a filter in bootstrap like this:
`SpringSecurityUtils.clientRegisterFilter 'restFilter', SecurityFilterPosition.ANONYMOUS_FILTER.order + 1`
It's adding the filter to the '/assets/**' URL pattern.  I don't want the restFilter applied to the pattern.

Should it only apply to the URL pattern's that don't have 'none'?  Should the clientRegisterFilter take in a URL pattern as a parameter to match on?  Is there another approach I'm not thinking of?

Thanks!
