### ISSUE TITLE
GPSPRINGSECURITYCORE-318: Another unnamed CacheManager already exists in the same VM in 2.0-SNAPSHOT

### ISSUE THREAD

**Issue by graemerocher** [grails-plugins/grails-spring-security-core#152]
Original Reporter: roos
Environment: Grails 2.4.4, Hibernate 4
Version: Grails-Spring-Security-Core 2.0
Migrated From: http://jira.grails.org/browse/GPSPRINGSECURITYCORE-318

Updated project to 2.0-SNAPSHOT-2015-03-04 to fix GPSPRINGSECURITYCORE-309 in a local project.
After that, application does not start with error "Another unnamed CacheManager already exists in the same VM". 
grails dbm-drop-all causes the same error.

Attached you find a Grails 2.4.4 upgraded functional-test-app based on #7a53fdf7 with enabled database-migration plugin.
Simply unpack, perform

```
./grailsw compile
grails dbm-drop-all --verbose --stacktrace
```

Workaround in my project is to set in DataSource.groovy:
 cache.region.factory_class = 'org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory'
 

error is:
```
Caused by: net.sf.ehcache.CacheException: Another unnamed CacheManager already exists in the same VM. Please provide unique names for each CacheManager in the config or do one of following:
1. Use one of the CacheManager.create() static factory methods to reuse same CacheManager with same name or create one if necessary
2. Shutdown the earlier cacheManager before creating new one with same name.
The source of the existing CacheManager is: DefaultConfigurationSource [ ehcache.xml or ehcache-failsafe.xml ]
	at net.sf.ehcache.CacheManager.assertNoCacheManagerExistsWithSameName(CacheManager.java:529)
	at net.sf.ehcache.CacheManager.init(CacheManager.java:374)
	at net.sf.ehcache.CacheManager.<init>(CacheManager.java:259)
	at org.hibernate.cache.ehcache.EhCacheRegionFactory.start(EhCacheRegionFactory.java:86)
	... 376 more
| Error Error executing script DbmDropAll: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManagerPostProcessor': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.spi.CacheImplementor]
Application context shutting down...
```

When downgrading to 2.0-RC4, it works again.

**Comment by mradzinski** [comment]
Environment: Grails 2.3.11, Hibernate 3.6.10.16
Version: Grails-Spring-Security-Core 2.0 R5

Same error is happening on latest release with default configuration. Not much more information to add since the stacktrace looks almost exactly like the one above.

**Comment by confile** [comment]
Environment: Grails 2.4.4, Hibernate 3.6.10.18
Version: Grails-Spring-Security-Core 2.0 RC5

Same error

**Comment by confile** [comment]
@graemerocher please reopen this issue.

**Comment by treble-snake** [comment]
Looks like Spring Security ACL plugin needs same changes as [Spring Security Core](https://github.com/grails-plugins/grails-spring-security-core/commit/8e2f9813e1efa4a3f17103fc2e2e02969178e653).
As a workaround you can add 
```
  aclCacheManager(EhCacheManagerFactoryBean) {
    cacheManagerName = 'spring-security-acl-cache-' + UUID.randomUUID()
  }
```
to *resourcers.groovy*.

**Comment by futu** [comment]
The bug reproduces when non-default datasources are used. Grails 2.3.5 (plug-in spring-security-core RC5)

**Comment by alvarosanchez** [comment]
This issue is caused by a bug in the database-migration plugin: https://jira.grails.org/browse/GPDATABASEMIGRATION-161

`runtime ":database-migration:1.4.1-SNAPSHOT"` fixes the issue
