### ISSUE TITLE
GPSPRINGSECURITYCORE-133: Incorrect behaviour of 'access' tag with 'url' attribute.

### ISSUE THREAD

**Issue by graemerocher** [grails-plugins/grails-spring-security-core#161]
Original Reporter: abeletski
Environment: Not Specified
Version: Not Specified
Migrated From: http://jira.grails.org/browse/GPSPRINGSECURITYCORE-133

WAR file has name "web" and application is available via url 'http://site.com/web/'.
When you try to use "sec:access url=..." you always don't have access.

    <sec:access url="${g.createLink(controller: 'contr', action: 'act')}">
       
    </sec:access>

Plugin uses:

    GrailsWebInvocationPrivilegeEvaluator.isAllowed(String contextPath, final String uri, final String method, final Authentication authentication).

    ...
    FilterInvocation fi = createFilterInvocation(contextPath, uri, method);
    ...

    protected FilterInvocation createFilterInvocation(final String contextPath, final String uri, final String method) {
       Assert.hasText(uri, "URI required");
       return new FilterInvocation(new DummyRequest(contextPath, method, contextPath + uri), DUMMY_RESPONSE, DUMMY_CHAIN);
    }

Attend that you pass "contextPath + uri" to dummy request's constructor. In case that I described above:
contextPath = /web
uri = /web/contr/act

contextPath + uri = /web/web/contr/act - It isn't correct path.

**Comment by burtbeckwith** [comment]
The context path is required by the underlying Spring Security functionality, so the plugin code needs to continue adding the context. Using `base:'/'` as described above seems like a good workaround.
