### ISSUE TITLE
GPSPRINGSECURITYCORE-305: auth.forceHttps can be sidestepped

### ISSUE THREAD

**Issue by graemerocher** [grails-plugins/grails-spring-security-core#170]
Original Reporter: edo
Environment: Java 1.7_67, win7-64, Grails 2.4.3
Version: Grails-Spring-Security-Core 2.0
Migrated From: http://jira.grails.org/browse/GPSPRINGSECURITYCORE-305

**Comment by burtbeckwith** [comment]
This setting only configures functionality in Spring Security, so the issue is there, not in the plugin.
