### ISSUE TITLE
GPSPRINGSECURITYCORE-253: AccessDeniedHandler: errorPage is not rendered within it's layout when adh.useForward is set

### ISSUE THREAD

**Issue by graemerocher** [grails-plugins/grails-spring-security-core#177]
Original Reporter: tcrossland
Environment: grails-spring-security-core 2.0-RC2, Grails 2.2.4, JDK 1.6.0_65
Version: Grails-Spring-Security-Core 2.0
Migrated From: http://jira.grails.org/browse/GPSPRINGSECURITYCORE-253

If the specified error page has a layout (`<meta name="layout" content="...">` ) the layout is not rendered when the AccessDeniedHandler forwards the request.

There is a workaround, by setting the errorPage to null and using a controller to render the view using a UrlMapping, for example:

```
"500"(controller: "error", action: "denied", exception: AccessDeniedException)
"403"(controller: "error", action: "denied")
```

(I had to specify the 403 as well for some reason, this also seems new with the 2.0-RC2 plugin).

**Comment by ddelponte** [comment]
Marking this as `Cannot Reproduce` and closing.

I will be happy to reopen it if you would be so kind as to attach or link to a sample app which reproduces the problem.

I have been unable to reproduce with the latest releases.
