### ISSUE TITLE
GPSPRINGSECURITYCORE-148: Redirect issue with Channel Security

### ISSUE THREAD

**Issue by graemerocher** [grails-plugins/grails-spring-security-core#201]
Original Reporter: derekslife
Environment: Grails 1.3.7
Version: Grails-Spring-Security-Core 1.2.6
Migrated From: http://jira.grails.org/browse/GPSPRINGSECURITYCORE-148

I have configured my login pages forced https. While the rest of the site forced http. Below are steps to recreate the problem. The following steps work as of version 1.1.3, however a 404/redirect issue prevents it from working in all 1.2 and later versions.

(Note: Using Grails 1.3.7)

Recreation Steps:
-------------------------------------
1  grails create-app exampleapp
2  cd exampleapp/
3  grails install-plugin spring-security-core 1.2.6
4  grails s2-quickstart com.exampleapp User Role
5  Append the following to the grails-app/conf/Config.groovy

    grails.plugins.springsecurity.secureChannel.definition = [
       '/login/**':                'REQUIRES_SECURE_CHANNEL',
       '/j_spring_security_check': 'REQUIRES_SECURE_CHANNEL',
       '/images/**':               'ANY_CHANNEL',
       '/css/**':                  'ANY_CHANNEL',
       '/js/**':                   'ANY_CHANNEL',
       '/**':                      'REQUIRES_INSECURE_CHANNEL'
    ]

6  grails run-app -https
7  Browse to http://localhost:8080/exampleapp/login

Problem: 404 is returned and browser is redirected to:
http://localhost:8080/exampleapp/grails/login/auth.dispatch

This doesn't seem to be correct behavior.

**Comment by burtbeckwith** [comment]
This is not an issue in Grails 3 since that dispatch approach is no longer used.
