### ISSUE TITLE
GPSPRINGSECURITYCORE-187: Spring security core plugin fails to deploy on JBOSS 7.1.3

### ISSUE THREAD

**Issue by graemerocher** [grails-plugins/grails-spring-security-core#209]
Original Reporter: hsn
Environment: JBOSS 7.1.3-SNAPSHOT
Version: Grails-Spring-Security-Core 1.2.7.3
Migrated From: http://jira.grails.org/browse/GPSPRINGSECURITYCORE-187

Grails application with spring security plugin installed fails to deploy on JBOSS 7.1.3-SNAPSHOT

Error messages are here: https://issues.jboss.org/browse/AS7-3719

1)
13:13:34,031 WARN [org.jboss.as.server.deployment] (MSC service thread 1-13) JBAS015893: Encountered invalid class name 'org.xmlpull.mxp1.MXParser,org.xmlpull.mxp1_serializer.MXSerializer' for service type 'org.xmlpull.v1.XmlPullParserFactory'

2)
{"JBAS014653: Composite operation failed and was rolled back. Steps that failed:" => {"Operation step-2" => {"JBAS014671: Failed services" => {"jboss.web.deployment.default-host.\"/nxd-0.1\"" => "org.jboss.msc.service.StartException in service jboss.web.deployment.default-host.\"/nxd-0.1\": JBAS018040: Failed to start context"},"JBAS014771: Services with missing/unavailable dependencies" => ["jboss.deployment.unit.\"nxd-0.1.war\".jboss.security.jacc Missing[JBAS014861: <one or more transitive dependencies>]"]}}}

**Comment by burtbeckwith** [comment]
Closing since the referenced bug report indicates it's fixed in JBoss 8
