### ISSUE TITLE
GPSPRINGSECURITYCORE-272: Add docs describing how to override login/logout controllers and GSPs

### ISSUE THREAD

**Issue by graemerocher** [grails-plugins/grails-spring-security-core#216]
Original Reporter: burtbeckwith
Environment: Not Specified
Version: Not Specified
Migrated From: http://jira.grails.org/browse/GPSPRINGSECURITYCORE-272

**Comment by ddelponte** [comment]
How to override:
1. `grails.plugin.springsecurity.LoginController.groovy`
2. `grails.plugin.springsecurity.LogoutController.groovy`
3. `grails-app/views/auth.gsp`

Is documented at https://grails-plugins.github.io/grails-spring-security-core/3.2.x/index.html#changes-in-generated-classes

I will close this issue
