### ISSUE TITLE
GPSPRINGSECURITYCORE-204: Unable build grails project with Maven for Spring-Security-Core-1.2.7.3

### ISSUE THREAD

**Issue by graemerocher** [grails-plugins/grails-spring-security-core#224]
Original Reporter: michwang
Environment: Not Specified
Version: Not Specified
Migrated From: http://jira.grails.org/browse/GPSPRINGSECURITYCORE-204

We have a mvn repo, I tried to run 'mvn clean package' on my STS(eclipse), the Spring-Security-Core-1.2.7.3 cannot be built under maven.

here's how I setup the dependency
<dependency>
            <groupId>org.grails.plugins</groupId>
            <artifactId>spring-security-core</artifactId>
            <version>1.2.7.3</version>
            <scope>provided</scope>
            <type>zip</type>
        </dependency>

The zip file is downloaded from our nexus repo, but failed to build

I've tried it with Grails 2.1.1, 2.1.3, 2.2.0
All got the same error

I have attached the log with this jira

Please take a look and help

**Comment by ddelponte** [comment]
This is an old bug report which references the spring-security-core release version from 2011.  The core of the issue appears to be maven configuration and is unrelated to the spring-security-core plugin itself.

If no one objects, I would like to close this issue.
