### ISSUE TITLE
GPSPRINGSECURITYCORE-310: documentation: allowing access to anybody on a controller action

### ISSUE THREAD

**Issue by graemerocher** [grails-plugins/grails-spring-security-core#235]
Original Reporter: flyingsaucer
Environment: Not Specified
Version: Not Specified
Migrated From: http://jira.grails.org/browse/GPSPRINGSECURITYCORE-310

Hi. Looking at [Defining Secured Annotations |http://grails-plugins.github.io/grails-spring-security-core/guide/single.html#securedAnnotations], I read:
{quote}
//...
Any user can access /myapp/secureAnnotated/anybody.
{quote}

Is that actually true? Wouldn't 'Pessimistic Lockdown', described just above that section as the default, block access to the un-annotated action?

**Comment by burtbeckwith** [comment]
Fixed by bf8624269f461e7303f0b54388df613570061a4e
