### ISSUE TITLE
GPSPRINGSECURITYCORE-244:   beforeDelete  on User not working from 2.0-RC1

### ISSUE THREAD

**Issue by graemerocher** [grails-plugins/grails-spring-security-core#237]
Original Reporter: xmlking
Environment: Grails 2.3.1 Hibernate 4 
Version: Grails-Spring-Security-Core 2.0
Migrated From: http://jira.grails.org/browse/GPSPRINGSECURITYCORE-244

I had following method in User class which was working fine before v2.0-RC1

```groovy
def beforeDelete(){
   UserRole.removeAll(this)
}
```

with v2.0-RC1, when  I try to delete user \[cascaded delete from Tenant class which has may users\] I am getting following error! 

```
No row with the given identifier exists: [com.xyz.User#7]. Stacktrace follows:
Message: No row with the given identifier exists: [com.xyz.User#7]
    Line | Method
->>   51 | doCall                   in com.xyz.UserRole$_removeAll_closure3
```

**Comment by Schlogen** [comment]
Created a sample app that couldn't reproduce the problem:

https://github.com/Schlogen/testSSC237

**Comment by alvarosanchez** [comment]
@Schlogen thank you very much. It doesn't reproduce indeed.
