### ISSUE TITLE
GPSPRINGSECURITYCORE-254: ip filter annotation or helper method

### ISSUE THREAD

**Issue by graemerocher** [grails-plugins/grails-spring-security-core#263]
Original Reporter: savcha
Environment: Not Specified
Version: Not Specified
Migrated From: http://jira.grails.org/browse/GPSPRINGSECURITYCORE-254

**Comment by ddelponte** [comment]
This issue was migrated over from our old JIRA account.  

I am opting to close it because there is no actionable information included in the description and the old JIRA ticket is no longer accessible.
