### ISSUE TITLE
GPSPRINGSECURITYCORE-75: None of the "Users" status informations should be exposed if the provided credentials ain't correct.

### ISSUE THREAD

**Issue by graemerocher** [grails-plugins/grails-spring-security-core#279]
Original Reporter: kosta
Environment: grails 1.3.7, jvm 1.6.24, kubuntu 10.04.2 LTS, 
Version: Grails-Spring-Security-Core 1.1.2
Migrated From: http://jira.grails.org/browse/GPSPRINGSECURITYCORE-75

When the wrong credentials are used in the auth.gsp form it should always lead to the same Exception, hence the form should always come up with the some error message: 

errors.login.fail -> "Sorry, we were not able to find a user with that username and password."

This is only the case for following configurations:
- fully functional Users (enabled: true)
- Users with expired password (passwordExpired: true, enabled: true)

In the other cases:
- disabled (enabled: false)
- expired (acountExpired: true, enabled: true)
- locked (accountLocked: true, enabled: true)

it shows a different error messages, even if the password is wrong (-> the incorrect credentials).

This exposes information about the existents of a certain username. 
Those informations/error messages should only be exposed if the User typed in the correct credentials (password).

**Comment by ddelponte** [comment]
I tend to think this is not a bug and is working as designed.

We could modify all of the i18n messages referenced in `authFail()` to be the same generic message by modifying the appropriate properties in `messages.properties`.

```
    def authfail() {

        String msg = ''
        def exception = session[WebAttributes.AUTHENTICATION_EXCEPTION]
        if (exception) {
            if (exception instanceof AccountExpiredException) {
                msg = messageSource.getMessage('springSecurity.errors.login.expired', null, "Account Expired", request.locale)
            } else if (exception instanceof CredentialsExpiredException) {
                msg = messageSource.getMessage('springSecurity.errors.login.passwordExpired', null, "Password Expired", request.locale)
            } else if (exception instanceof DisabledException) {
                msg = messageSource.getMessage('springSecurity.errors.login.disabled', null, "Account Disabled", request.locale)
            } else if (exception instanceof LockedException) {
                msg = messageSource.getMessage('springSecurity.errors.login.locked', null, "Account Locked", request.locale)
            } else if (exception instanceof SessionAuthenticationException) {
                msg = messageSource.getMessage('springSecurity.errors.login.max.sessions.exceeded', null, "Sorry, you have exceeded your maximum number of open sessions.", request.locale)
            } else {
                msg = messageSource.getMessage('springSecurity.errors.login.fail', null, "Authentication Failure", request.locale)
            }
        }

        if (springSecurityService.isAjax(request)) {
            render([error: msg] as JSON)
        } else {
            flash.message = msg
            redirect action: 'auth', params: params
        }
    }
```

Developers could then modify their local `messages.properties` however they see fit, providing more specifics if needed.

Any and all feedback is welcome :)

The other option, which I'm in favor of, is to just leave the code as is.

**Comment by ddelponte** [comment]
Marking this as `Not A Bug` and closing.
