### ISSUE TITLE
GPSPRINGSECURITYCORE-43: Addition of non-subclass of RoleVoter

### ISSUE THREAD

**Issue by graemerocher** [grails-plugins/grails-spring-security-core#308]
Original Reporter: richkroll
Environment: Not Specified
Version: Grails-Spring-Security-Core 1.1
Migrated From: http://jira.grails.org/browse/GPSPRINGSECURITYCORE-43

**Comment by ddelponte** [comment]
This issue was migrated over from our old JIRA account.  

I am opting to close it because there is no actionable information included in the description and the old JIRA ticket is no longer accessible.
