### ISSUE TITLE
GPSPRINGSECURITYCORE-117: AnnotationFilterInvocationDefinition ignores excluded in URLMapping

### ISSUE THREAD

**Issue by graemerocher** [grails-plugins/grails-spring-security-core#339]
Original Reporter: tobad357
Environment: Not Specified
Version: Not Specified
Migrated From: http://jira.grails.org/browse/GPSPRINGSECURITYCORE-117

When using a catch all URLMapping (/**) the AnnotationFilterInvocationDefinition will mapp all urls to it including urls that match an exclude
This causes issues when the catch all has security annotations on them as the login page can't load css, js, images etc if they are in the exclude

A suggested fix would be to add the following exclude check which seems to work

    if (!UrlMappingsFilter.isUriExcluded(_urlMappingsHolder, requestUrl)) {
       for (UrlMappingInfo mapping : _urlMappingsHolder.matchAll(requestUrl)) {
          configureMapping(mapping, grailsRequest, savedParams);

          url = findGrailsUrl(mapping);
          if (url != null) {
             break;
          }
       }
    }

**Comment by burtbeckwith** [comment]
This is a fairly obscure Grails feature, and with the rework done in Grails 3 you can still specify excludes but they're ignored at runtime. Version 3.x of the plugin has support for defining patterns that should have no processing done on them - see https://grails-plugins.github.io/grails-spring-security-core/v3/index.html#chainmap (see the `filters: 'none'` example)
