### ISSUE TITLE
Upgrade to Grails 3.x

### ISSUE THREAD

**Issue by erickmelo** [grails-plugins/grails-spring-security-core#362]
I have been following the discussions in the mailing list, the possibility of this plugin be discontinued in  Grails 3.x. Is there any consolidated position on this? 

I believe that the adoption of Grails 3.x can be quite impacted accordingly. Some projects are in our stand-by waiting for the update to version 3.x of spring-security suite (core / ldap / acl).

**Comment by Omasiri** [comment]
Hello @erickmelo,

Grails-spring-security-core will have a grails 3 version.  A separate grails 3 branch may be available soon. Please take a look at https://github.com/grails-plugins/grails-spring-security-core/pull/361.

**Comment by erickmelo** [comment]
@Omasiri 
Thanks for the answer. Would you have any update perspective of other related plugins (LDAP, ACL, etc.)

**Comment by burtbeckwith** [comment]
I'm working on getting the 2.0 final release out. I released RC5 last week and I'm finishing up the issues that will be included in the GA release (some will have to wait for a 2.0.x or 2.1 release). Once that's done I'll update the secondary plugins (ldap, ui, etc.) to use the 2.0 plugin, and will also merge in the PR from @Omasiri and make that available. Once that's out I'll update the secondary plugins again to work in Grails 3.

**Comment by Labi0** [comment]
I am working on making acl support grails 3 as well.

**Comment by ikakara** [comment]
@burtbeckwith - when you're upgrading the secondary plugins, do you mind creating a checklist?  I'd like to upgrade a (secondary) plugin I created for spring-security too.  It would be a huge help :+1:
