### ISSUE TITLE
Grails 2.5.0 + SSC 2.0-RC5 - Broken apf.postOnly default

### ISSUE THREAD

**Issue by yuri1969** [grails-plugins/grails-spring-security-core#366]
My application is based on Grails 2.5.0 with SSC 2.0-RC5 and utilises the HTML form based authentication. 

Despite DefaultSecurityConfig.groovy having apf.postOnly set to true and http://grails-plugins.github.io/grails-spring-security-core/guide/urlProperties.html mentioning to postOnly defaulting to true, tests discovered I was in fact able to log in via HTTP GET.

Setting grails.plugin.springsecurity.apf.postOnly = true explicitly in the Config.groovy fixes this issue.

**Comment by burtbeckwith** [comment]
This setting refers to logout, not login

**Comment by yuri1969** [comment]
That seems strange to me. I thought the grails.plugin.springsecurity.logout.postOnly setting handles logout filtering. Also the user guide linked above mentions directly: "Whether to allow only POST login requests" for the apf.postOnly flag.

Still, setting grails.plugin.springsecurity.apf.postOnly to true prevents you from logging in via GET.
