### ISSUE TITLE
3.0.0.M1 -> Securing Controllers much more difficult in 3.0

### ISSUE THREAD

**Issue by codeconsole** [grails-plugins/grails-spring-security-core#370]
2 issues:

in 2.5, you could do this:

    grails.plugin.springsecurity.controllerAnnotations.staticRules = [
        '/car/index':                  ['isAuthenticated()'],
    }

with the following UrlMappings.groovy

    "/$controller/$action?/$id?(.$format)?" 
    "/cars"(resources: "car") 
    "/"(controller:"car")	

That one rule would secure /car/index, /cars and / (basically all calls to the index method on CarController.

With 3.0, all it secures is the one url /car/index.

The second issue is placing @Secured annotation on the index method does not secure /cars.  It only secures /car/index as well.

**Comment by codeconsole** [comment]
I believe this bug may be specific to Grails 3.0.7 and Grails 3.0.8 and that the desired behavior works in 3.0.6
https://github.com/grails-plugins/grails-spring-security-core/issues/384

**Comment by codeconsole** [comment]
I believe this bug may be specific to Grails 3.0.7 and Grails 3.0.8 and that the desired behavior works in 3.0.6

I meant to reference 
https://github.com/grails-plugins/grails-spring-security-core/issues/385

**Comment by alvarosanchez** [comment]
Closing as duplicate as per last comment.
