### ISSUE TITLE
3.0 Changing controllerAnnotations.staticRules in application.groovy requires restart

### ISSUE THREAD

**Issue by codeconsole** [grails-plugins/grails-spring-security-core#371]
Changing a security rule in application.groovy requires a server restart.  This makes testing new rules very difficult.  The changes should be reloaded automatically like it worked in 2.5

**Comment by burtbeckwith** [comment]
This is likely a Grails issue - the config loading and handling changed quite a lot in 3.0. Do non-security-related changes work without a restart?

**Comment by codeconsole** [comment]
I'll resolve this as it being a Grails issue because with the latest Grails it now works. Changes are picked up right away.
