### ISSUE TITLE
@Secured not working when custom url mapping is used

### ISSUE THREAD

**Issue by damluar** [grails-plugins/grails-spring-security-core#373]
When I annotate my controller with 

    @Secured(['ROLE_USER'])
    class UserController {
        ....
    }

and I use the default url mapping for controllers, I can access the page as expected.
But when I specify a mapping like the following:

    '/api/user'(resources: 'user')

I get 403 forbidden response although the user has required role.
Is it a bug or is it by design?

**Comment by alvarosanchez** [comment]
Which version of the plugin are you working with?

**Comment by magnomp** [comment]
I'm not the original poster, but experienced the same issue with plugin version 3.0.0.M1

**Comment by nayankWebonise** [comment]
I am facing similar issue where in i have a custom url mapping
/api/user (controller:"user", action:"getAllUsers",method:"GET")

if i access via controller mapping , i am able to access it but not from custom url mapping.

Is this completed?

**Comment by xfermi** [comment]
+1 ;-( 

grails-security: 3.0.0.M1
grails: 3.0.9

**Comment by nayankWebonise** [comment]
I Got it working for my app.

Just add it in static rules and give it a role.
'/api/**' : ['ROLE_ADMIN']

it will register your custom URLs.
Thanks
Nayan Kakati

**Comment by pabloalba** [comment]
Same problem here.

grails-security Version: 3.0.0.M1
Grails Version: 3.0.9
Groovy Version: 2.4.5
JVM Version: 1.7.0_65

**Comment by rscorer** [comment]
If you follow the tutorial in 3.0.0.M1 it fails to work correctly once you add the Secured annotation

I continually get the message that I don't have access - for now I'm putting everything in the static rules. Not too big a problem, nice to know its not me :) 
Thanks!

**Comment by burtbeckwith** [comment]
Fixed in 3.0.0.M2

**Comment by imarban** [comment]
It is also happening for 3.1.1
