### ISSUE TITLE
Removing properties from User class leads to authentication failure

### ISSUE THREAD

**Issue by damluar** [grails-plugins/grails-spring-security-core#374]
I generated the domain classes using s2 script. Now I removed some fields that I don't need like `accountLocked`, `accountExpired`. This leads to not being able to login at runtime.
The documentation says that `username, enabled, password are the default names of the core required properties`, so I assume that other fields are optional. Or are all the fields required?

**Comment by burtbeckwith** [comment]
They are required, but only with the default UserDetailsService implementation (GormUserDetailsService). You can remove them if you want, but you would need to create a custom UserDetailsService (it's very easy to do, see the docs for info). Spring Security needs a username, password, granted roles, and those 4 booleans, but the data can come from anywhere and you can hard-code the boolean values if you don't use/change them in your app. The booleans are configured in the generated code with default values that let you ignore them - you only need to provide the username and password.

**Comment by damluar** [comment]
Thank you for always competent answers!

I decided to go with: `static transients = ['accountExpired', 'accountLocked', 'springSecurityService']`

From looking at the code 
  
    String accountExpiredPropertyName = conf.userLookup.accountExpiredPropertyName
    boolean accountExpired = accountExpiredPropertyName ? 
                                         user."$accountExpiredPropertyName" : false

another option would be to override `userLookup.accountExpiredPropertyName = ''`, then the default value will be used.
