### ISSUE TITLE
@Secured annotation inheritance doesn't work with spring-security-core:2.0-RC4

### ISSUE THREAD

**Issue by VitaliiH** [grails-plugins/grails-spring-security-core#376]
Issue is related to https://github.com/grails-plugins/grails-spring-security-core/issues/106, which is already closed. I'm not able to reopen it, so I created a new one.
I use grails 2.3.5. Bug reproduces with versions of spring-security-core 2.0, 2.0-RC4, 2.0-RC5.
After some investigation, I found how to fix it.
In class `AnnotationFilterInvocationDefinition` method `findActionRoles(final Class<?> clazz)` which is repsonsible for check whether Controller's method is annotated or not, doesn't check inherited methods at all.
To change this behavior, the loop inside this method should be changed from 
`for (Method method : clazz.getDeclaredMethods())`
to
`for (Method method : clazz.getMethods())`
I checked, this change helps to solve the issue.

**Comment by magx2** [comment]
+1 have the same problem!

**Comment by vvov4ikk** [comment]
+1

**Comment by burtbeckwith** [comment]
Fixed in 2.0-RC6 and 3.0.0.M2

**Comment by VitaliiH** [comment]
Good news, thank you!

**Comment by GlamourOff** [comment]
We are so happy!
