### ISSUE TITLE
respond method doesn't render with layout "main"

### ISSUE THREAD

**Issue by gykpro** [grails-plugins/grails-spring-security-core#380]
I can't get "Secured" annotated controller action work with respond method, but render method is alright.

Version: grails 3.0.3/3.0.4
What I have done:

```
grails create-app security_render

cd security_render
```

add 

```
compile 'org.grails.plugins:spring-security-core:3.0.0.M1'
```

to build.gradle

```

grails

create-domain-class com.test.security.myDomain

generate-all com.test.security.MyDomain 

s2-quickstart com.autobole.security User Role

```

Then add some test user in Bootstrap.groovy
```
		def adminRole = new Role('ROLE_ADMIN').save()
		def userRole = new Role('ROLE_USER').save()

		def testUser = new User('me', 'password').save()

		UserRole.create testUser, adminRole, true
```

add an annotation in MydomainController.groovy
```
    @Secured('ROLE_ADMIN')
    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond MyDomain.list(params), model:[myDomainCount: MyDomain.count()]
    }

```

After I logged in with testuser, I get following message:
![image](https://cloud.githubusercontent.com/assets/495825/10266348/55a4b238-6a8d-11e5-95fc-e66867707bf2.png)

According to the HTML source code, there is nothing from main.gsp

If I user render instead of respond, everything works fine:
```
    @Secured('ROLE_ADMIN')
    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        render view:"index", model:[myDomainList: MyDomain.list(params), myDomainCount: MyDomain.count()]
    }

```
![image](https://cloud.githubusercontent.com/assets/495825/10266354/dfaaadb6-6a8d-11e5-975c-aea3f314ffcf.png)

So, how do I get respond method work?

**Comment by burtbeckwith** [comment]
This works fine for me, I get identical HTML with render and respond. Try deleting the `build` directory, and updating to 3.0.0.M2 if that doesn't help. If it's still broken create a small test app (e.g. on GitHub) and I'll take a look.
