### ISSUE TITLE
3.0.0.M1 -> s2-quickstart default configuration doesn't correctly make /index public

### ISSUE THREAD

**Issue by codeconsole** [grails-plugins/grails-spring-security-core#384]
On all versions of Grails 3.0.x, both / and /index result in a redirect to /login/auth with the generated staticRules.  Is seems that the rule for index is completely ignored.

	grails.plugin.springsecurity.controllerAnnotations.staticRules = [
		'/':                ['permitAll'],
		'/error':           ['permitAll'],
		'/index':           ['permitAll'],
		'/index.gsp':       ['permitAll'],
		'/shutdown':        ['permitAll'],
		'/assets/**':       ['permitAll'],
		'/**/js/**':        ['permitAll'],
		'/**/css/**':       ['permitAll'],
		'/**/images/**':    ['permitAll'],
		'/**/favicon.ico':  ['permitAll']
	]

This problem can be demonstrated with the following simple grails 3.0.8 example app:
https://github.com/codeconsole/grails3bugs

**Comment by codeconsole** [comment]
May be related to https://github.com/grails-plugins/grails-spring-security-core/issues/370

**Comment by codeconsole** [comment]
I incorrectly referenced this issue.  I believe this specifically is a Spring Security Plugin bug as all versions of Grails 3.0.x experience the same behavior.

**Comment by codeconsole** [comment]
confirmed the rule is actually related.

changing the rules to 

	grails.plugin.springsecurity.controllerAnnotations.staticRules = [
		'/':                ['permitAll'],
		'/error':           ['permitAll'],
		'/index':           ['permitAll'],
		'/index*':       ['permitAll'],
		'/shutdown':        ['permitAll'],
		'/assets/**':       ['permitAll'],
		'/**/js/**':        ['permitAll'],
		'/**/css/**':       ['permitAll'],
		'/**/images/**':    ['permitAll'],
		'/**/favicon*':  ['permitAll']
	]

fixes the issue

**Comment by Schlogen** [comment]
After some debugging the core of the issue is having index.gsp. Grails will take the 2 separate keys `index` and `index.gsp` and convert them into a single entry with a sub entry "gsp". Then there is code in the plugin to remove entries that have a value being a `Map`. This ends up removing `/index` all together.

**Comment by hakanernam** [comment]
@codeconsole @Schlogen Thanks. I  had to set 'rejectIfNoRule' and 'rejectPublicInvocations' both to false to get the index page for a new test application last night and was really frustrated by having to do this. Wish I had checked the issues sooner.

Workaround works. But it could be compressed to just one rule based on stated grails behavior
´´´
 '/index*':          ['permitAll'],
´´´

**Comment by alvarosanchez** [comment]
Duplicated by #385
