### ISSUE TITLE
3.0.0.M1 -> authAjax currently returns a status 200 with /authAjax using Grails 3

### ISSUE THREAD

**Issue by codeconsole** [grails-plugins/grails-spring-security-core#386]
it should return the correct status code for UNAUTHORIZED.  This was how all previous versions of this plugin worked.

The following pull request is a simple fix to this issue:
https://github.com/grails-plugins/grails-spring-security-core/pull/383

**Comment by burtbeckwith** [comment]
Fixed in 3.0.0.M2
