### ISSUE TITLE
springSecurityService.getCurrentUser() method does not exists

### ISSUE THREAD

**Issue by salex772** [grails-plugins/grails-spring-security-core#389]
I use spring-security-core:3.0.0.M1 in grails project.
After successful DI into controller springSecurityService does not contain these methods:
springSecurityService.currentUser
springSecurityService.getCurrentUser()
springSecurityService.loadCurrentUser()

But it must has, as I read in documentation
GitHub issue http://stackoverflow.com/questions/32669708/null-pointer-on-springsecurityservice-currentuser

**Comment by salex772** [comment]
Any comment?

**Comment by ejaz-ahmed** [comment]
I am using it with grails 3.0.9 and I am extensively using springSecurityService.getCurrentUser() method in my application to resolve tenant. I've commented on your SO question too. Try Gradle:run task.

**Comment by burtbeckwith** [comment]
I have no idea why this would fail - you can see the methods in the source: https://github.com/grails-plugins/grails-spring-security-core/blob/master/grails-app/services/grails/plugin/springsecurity/SpringSecurityService.groovy

**Comment by salex772** [comment]
Yes, I saw it, but it's a fact - at a runtime there isn't such method

2015-10-29 14:00 GMT+03:00 Burt Beckwith <notifications@github.com>:

> I have no idea why this would fail - you can see the methods in the
> source:
> https://github.com/grails-plugins/grails-spring-security-core/blob/master/grails-app/services/grails/plugin/springsecurity/SpringSecurityService.groovy
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grails-plugins/grails-spring-security-core/issues/389#issuecomment-152146979>
> .
>



-- 
____________________________________
Salex S.

**Comment by burtbeckwith** [comment]
Is it possible that someone has overridden that bean? This would happen if you created a service in grails-app/services with the name SpringSecurityService, but in any package. It could also have been done in resources.groovy, or another plugin.

**Comment by burtbeckwith** [comment]
Closing as can't reproduce, since this is likely specific to this application, and if it were a real bug it would have affected everyone.

**Comment by ejaz-ahmed** [comment]
@burtbeckwith It is random and I've also faced this issue and for my case it appears if I run grails application by running Application.groovy. Gradle:bootRun works fine. It is quite strange but I've observed this also.

**Comment by ejaz-ahmed** [comment]
Considering the importance of other issues, I would suggest not to invest time on this.

**Comment by salex772** [comment]
I found a solution. The problem was in my custom UserDetailsService. I didn't find what was wrong but when I switched tp plugin the method becime available.

'''
package com.xxx.security

import com.xxx.gorm.security.User
import grails.plugin.springsecurity.userdetails.GormUserDetailsService
import grails.plugin.springsecurity.userdetails.NoStackUsernameNotFoundException
import grails.transaction.Transactional
import org.slf4j.Logger
import org.slf4j.LoggerFactory
import org.springframework.security.core.GrantedAuthority
import org.springframework.security.core.userdetails.UserDetails
import org.springframework.security.core.userdetails.UsernameNotFoundException

/**
 * This make possible to authenticate through a user UID and login fields
 * by default authentication is done by email field
 * 
 */
class ExtendedUserDetailsService extends GormUserDetailsService {

	protected Logger logger = LoggerFactory.getLogger(getClass())

	@Override
	@Transactional(readOnly = true, noRollbackFor = [IllegalArgumentException, UsernameNotFoundException])
	UserDetails loadUserByUsername(String username, boolean loadRoles) throws UsernameNotFoundException {

		def user = User.findWhere(email: username)
		if (!user) {
			user = User.findWhere(login: username)
			if (!user) {
				user = User.findWhere(uid: username.toInteger())
				if (!user) {
					logger.warn 'User not found: {}', username
					throw new NoStackUsernameNotFoundException()
				}
			}
		}

		Collection<GrantedAuthority> authorities = loadAuthorities(user, username, loadRoles)
		createUserDetails(user, username, authorities)
	}

	protected static UserDetails createUserDetails(User user, String username, Collection<GrantedAuthority> authorities) {

		new DbstCurrentUser(username, user, authorities)
	}

}
'''

And this is my custom user service

'''
package com.xxx.security

import com.xxx.gorm.security.User
import grails.plugin.springsecurity.userdetails.GrailsUser
import org.springframework.security.core.GrantedAuthority
/**
 * Represents userDetail (acts as a proxy class between domain class and current web user)
 * Created by salex on 19.09.2015.
 */
class DbstCurrentUser extends GrailsUser {

	private User user

	DbstCurrentUser(String username, User user, Collection<GrantedAuthority> authorities) {
		super(username, user.password, user.enabled, !user.accountExpired, !user.passwordExpired, !user.accountLocked, authorities, user.id)
		this.user = user

	}

	public User getUser() {
		return user;
	}

	public Role getRoles() {
		return user.roles;
	}

	@Override
	String toString() {
		return user.name + " (" + user.uid + ") " + user.email
	}
}
'''
