### ISSUE TITLE
3.0.0.M1 > filterchain.chainmap is interpretting 'dot' in uri

### ISSUE THREAD

**Issue by orubel** [grails-plugins/grails-spring-security-core#392]
If you pass a '.' as part of the URI, this gets interpretted and throws an error.

ex. 
grails.plugin.springsecurity.filterChain.chainMap = [
        '/v0.1/**' : 'none'
]

It seems to be parsing/splitting the string into two parts at the 'dot'

**Comment by alvarosanchez** [comment]
Duplicates #385
