### ISSUE TITLE
Can't support SpringSecurity4.0+

### ISSUE THREAD

**Issue by hanyou** [grails-plugins/grails-spring-security-core#397]
I use grails websocket,  but need springsecurity4.0+, how to update springsecurity4.0+

**Comment by burtbeckwith** [comment]
The 3.0.0 plugin uses Spring Security 4.0.3

**Comment by hanyou** [comment]
release time?

**Comment by burtbeckwith** [comment]
About 20 hours ago: https://bintray.com/grails/plugins/spring-security-core/3.0.0/view - docs are at https://grails-plugins.github.io/grails-spring-security-core/

**Comment by hanyou** [comment]
very good
