### ISSUE TITLE
3.0.0 version has no i18n files.

### ISSUE THREAD

**Issue by akozel** [grails-plugins/grails-spring-security-core#398]
3.0.0 version has no i18n files.
https://i.gyazo.com/e2d121688da90ac1ce1a487a73bb3e8c.png

**Comment by burtbeckwith** [comment]
What version of Grails are you using?

**Comment by akozel** [comment]
Grails version is 3.1.0.M3

**Comment by burtbeckwith** [comment]
I think you're seeing https://github.com/grails/grails-core/issues/9459 which was fixed after M3 was released. The plugin jar does include the properties files and they're correctly resolved in 3.0, so regardless this is a Grails issue. Until it's fixed you can copy the plugin's files into your app's i18n folder

**Comment by akozel** [comment]
thank you :)
