### ISSUE TITLE
UserRole.remove signature or return type issue

### ISSUE THREAD

**Issue by robertoschwald** [grails-plugins/grails-spring-security-core#405]
In 3.0.0, UserRole.remove() is:

```
static boolean remove(User u, Role r, boolean flush = false) {
		if (u == null || r == null) return false
		int rowCount = UserRole.where { user == u && role == r }.deleteAll()
		if (flush) { UserRole.withSession { it.flush() } }
		rowCount
}
```

So either the signature must be changed to return an int, or a boolean should be returned (as it was in older plugin versions)

**Comment by alvarosanchez** [comment]
In this case, I think the integer will be coerced to a boolean following the groovy truth.
