### ISSUE TITLE
spring-security-core 3.0.1 won't run on Java 7

### ISSUE THREAD

**Issue by mjcmatrix** [grails-plugins/grails-spring-security-core#407]
A simple s2-quickstart 'hello world' test app that depends on spring-security-core 3.0.1 will compile but not run in a Java 7 build environment due to version 52 class files compiled with Java 8 in spring-security-core.

(3.0.0 does not have this dependency but 'hello world' will not run without workarounds either due to issues such as #401.)

Is Java 8 now the minimum compile version for a secure Grails app, i.e. is this intentional?

Exception java.lang.UnsupportedClassVersionError is thrown on 'grails run-app'. Stack trace snippet:

    Caused by: java.lang.UnsupportedClassVersionError: grails/plugin/springsecurity/SpringSecurityCoreGrailsPlugin : Unsupported major.minor version 52.0
    	at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.7.0_91]

This is in environment:

    Java version "1.7.0_91"
    OpenJDK Runtime Environment (IcedTea 2.6.3) (7u91-2.6.3-0ubuntu0.14.04.1)
    OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)
    
    Grails 3.1.0.RC1

Steps to reproduce:

    grails create-app testproject
    cd testproject
    # Add spring-security-core dependency to build.gradle as per 'Getting Started guide'
    grails compile
    grails s2-quickstart co.example User Role --groupClassName=RoleGroup
    grails run-app

**Comment by mjcmatrix** [comment]
Ubuntu 14.04 LTS (chosen server and desktop platform) does not have OpenJDK 8 yet in official packages. The proprietary Oracle 8 installer will have to be used.

**Comment by mjcmatrix** [comment]
Same app runs fine on (Oracle) Java 8.

**Comment by mjcmatrix** [comment]
Thanks Burt.

**Comment by burtbeckwith** [comment]
Fixed in 3.0.2
