### ISSUE TITLE
Using UUIDs in Domainclasses

### ISSUE THREAD

**Issue by bresche** [grails-plugins/grails-spring-security-core#408]
I use the spring security 2 plugin with grails 2.5.1. All our domains are using UUIDs

```java
String id
static mapping = {
	id generator: 'uuid', length: 32
}
```

I have generated spring security domains with roleGroups.

```java
static RoleGroupRole get(long roleGroupId, long roleId) {
   criteriaFor(roleGroupId, roleId).get()
}
```

Now i have to change all method from long to String.

Is there another way to use UUIDs?

**Comment by burtbeckwith** [comment]
The generated classes are there to get you started - in this case you just need to make these changes once and you should be all set.
