### ISSUE TITLE
Registered filters are not deregistered

### ISSUE THREAD

**Issue by Schlogen** [grails-plugins/grails-spring-security-core#409]
https://github.com/grails-plugins/grails-spring-security-core/blob/master/src%2Fmain%2Fgroovy%2Fgrails%2Fplugin%2Fspringsecurity%2FSpringSecurityCoreGrailsPlugin.groovy#L612 is not including filters registered with `SpringSecurityUtils.registerFilter` in a plugin

**Comment by burtbeckwith** [comment]
Fixed in 3.0.3
