### ISSUE TITLE
GormUserDetailsService throws NoStackUsernameNotFoundException whereas DefaultAuthenticationEventPublisher expects UsernameNotFoundException

### ISSUE THREAD

**Issue by abhilakshsharmattn** [grails-plugins/grails-spring-security-core#410]
I think I have found an issue in spring-security plugin.
When I set 
<b>grails.plugin.springsecurity.useSecurityEventListener = true
grails.plugin.springsecurity.dao.hideUserNotFoundExceptions = false</b>

and try to login with a username that never existed, it would not fire <b>AuthenticationFailureBadCredentialsEvent</b>.

The reason I am able to find is:
in <b>DefaultAuthenticationEventPublisher</b> exception mapping is added for <b>"UsernameNotFoundException"</b> and <b>"AuthenticationFailureBadCredentialsEvent" </b>
whereas in <b>GormUserDetailsService</b> if user is not found then <b>"NoStackUsernameNotFoundException"</b> is thrown.

So <b>DefaultAuthenticationEventPublisher</b> is not able to map it to any event.

**Comment by burtbeckwith** [comment]
Until this is fixed in the next release, there's a simple workaround. Redefine the "authenticationEventPublisher" bean in resources.groovy, and set the `additionalExceptionMappings` property with a Properties instance with the full class name of NoStackUsernameNotFoundException as the key and the full class name of AuthenticationFailureBadCredentialsEvent as the value:

    import grails.plugin.springsecurity.userdetails.NoStackUsernameNotFoundException
    import org.springframework.security.authentication.DefaultAuthenticationEventPublisher
    import org.springframework.security.authentication.event.AuthenticationFailureBadCredentialsEvent

    beans = {
       authenticationEventPublisher(DefaultAuthenticationEventPublisher) {
          additionalExceptionMappings =
             ([(NoStackUsernameNotFoundException.name): AuthenticationFailureBadCredentialsEvent.name] as Properties)
       }
    }

**Comment by burtbeckwith** [comment]
Fixed in v3.0.4
