### ISSUE TITLE
Controller MetaClass Methods Result in MissingPropertyException

### ISSUE THREAD

**Issue by atreides322** [grails-plugins/grails-spring-security-core#415]
When I try to use any of the controller metaclass methods, I get a `groovy.lang.MissingPropertyException: No such property: principal for class: HomeController` If I enable trace logs for grails.plugin.springsecurity, I can see `doWithDynamicMethods` getting invoked. In `BootStrap.init()`, I can invoke `HomeController.metaClass.respondsTo(null, 'getPrincipal')` and see that a `ClosureMetaMethod` gets returned. However, inside the controller, that same method returns an empty list. I'm running into this with Spring Security Core 3.0.3 and Grails 3.0.12 and Grails 3.0.14.

**Comment by burtbeckwith** [comment]
This is a problem with Grails, not the plugin - see https://github.com/grails/grails-core/issues/9648
