### ISSUE TITLE
SecurityTagLib.groovy @ 118

### ISSUE THREAD

**Issue by kszymko** [grails-plugins/grails-spring-security-core#416]
On one of our gsp files we render:

`userSex: '<view:loggedInUserInfo field="sex"/>'`

which might have values: 1 or 0 and later on we have some logic which utilizes this variable.
Somehowe for female users (sex = 0) our tests were failing. So we started invastigating:

Looks like here is the problem:

grails-spring-security-core/grails-app/taglib/grails/plugin/springsecurity/SecurityTagLib.groovy @ 118

namely:

`if (source) {`

when we changed it to:

`if (source != null) {`

all our tests passed.

**Comment by burtbeckwith** [comment]
Fixed in v3.0.4
