### ISSUE TITLE
Document what URL use in static rules

### ISSUE THREAD

**Issue by bgoetzmann** [grails-plugins/grails-spring-security-core#417]
Document that you don't have to use mapped URL but URL resolved controller in static rules.
Please, see:
https://grails.slack.com/archives/questions/p1455738057000653

**Comment by sdelamo** [comment]
@bgoetzmann in the provided slack link I don't find the question or conversation you are refering to. Could you paste here the snippet of conversation you are refering to?

**Comment by ddelponte** [comment]
It's been > 2 years since this issue was created.  
No feedback  has been received.  
Closing.
