### ISSUE TITLE
grails.plugin.springsecurity.ReflectionUtils.getRequestMapClass() is unable to find Requestmap class when grails 3.1.1 app is deployed as .war in tomcat.

### ISSUE THREAD

**Issue by Omasiri** [grails-plugins/grails-spring-security-core#422]
For some reason
Grails 3.1.1 application runs from command line without problems. However tomcat fails to deploy the same application .war file with the following error message:

...
...
`Caused by: java.lang.AssertionError: Cannot load Requestmaps; 'requestMap.className' property 'com.novadge.security.Requestmap' is invalid. Expression: Requestmap. Values: Requestmap = null`
...
...

If I create a demo grails app without running `grails s2-quickstart com.novadge.security Users Role Requestmap`, tomcat deploys the app .war file without problems.

**Comment by bilgehanm** [comment]
Have same problem. A grails 3.1 application runs fine from command line or ide without problems, can't deploy to tomcat.

`ERROR org.springframework.boot.SpringApplication - Application startup failed
org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'filterInvocationInterceptorDeregistrationBean': Cannot resolve reference to bean 'filterInvocationInterceptor' while setting bean property 'filter'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'filterInvocationInterceptor': Invocation of init method failed; nested exception is java.lang.AssertionError: Cannot load Requestmaps; `

**Comment by Omasiri** [comment]
OS: Windows 10.

To reproduce, add  `compile "org.grails.plugins:aws-sdk:1.10.51"` to build.gradle

For my plain project I had the following in build.gradle
`compile 'mysql:mysql-connector-java:5.1.29'
    compile(group: 'org.grails.plugins', name: 'spring-security-core', version: '3.0.3')
compile 'org.grails.plugins:excel-import:3.0.0.RC2'
    compile 'org.grails.plugins:excel-export:2.0.1'
compile 'org.grails.plugins:aws-sdk:1.10.51'`

**Comment by burbidge** [comment]
Was there any resolution to this?

**Comment by ddelponte** [comment]
@burbidge it does not look like there was any resolution.  

@burtbeckwith was not able to reproduce the issue.
