### ISSUE TITLE
Grails Spring Security Plugins not binary compatible with Grails 3.1.x

### ISSUE THREAD

**Issue by dariusan** [grails-plugins/grails-spring-security-core#426]
Cannot use spring security plugins with grails 3.1.x -> `Caused by: java.lang.ClassNotFoundException: org.grails.datastore.gorm.GormEntity$Trait$FieldHelper`

According to: https://grails.org/single-page-documentation.html  chapter: 3.1 
there is an issue:

> You are using a plugin or class that was compiled with a previous version of GORM and these will need to be recompiled to be Grails 3.1 and GORM 5 compatible.

**Comment by burtbeckwith** [comment]
There are no domain classes in the core plugin

**Comment by dariusan** [comment]
How about ACL?
