### ISSUE TITLE
Spring Boot management interface security not working

### ISSUE THREAD

**Issue by gregopet** [grails-plugins/grails-spring-security-core#429]
I have a problem where the Spring Boot default management and healthcheck endpoints cannot check whether the user is authenticated. The result is that I can only block the healthcheck endpoints or display their entire contents to everyone.

The problem is that Spring Boot cannot find the `org.springframework.security.config.http.SessionCreationPolicy` class which it uses to determine whether Spring Security is loaded (in `ManagementServerProperties.maybeCreateSecurity`). Another symptom of this (and an easy way to test) is that setting `management.security.enabled: true` in my `application.yml` will cause the app startup to fail (because there seems to be no security implementation).

Our workaround was to simply copy the `SessionCreationPolicy` enumeration into our project from Spring Security sources.

We found the bug using both 3.0.4 as well as 3.1.1 versions of the plugin, with Grails 3.1.5 and 3.1.6

**Comment by sdelamo** [comment]
I've created an example of Grails 3 using Spring Boot Actuator /health endpoint secured by Spring Security Core: 

https://github.com/grails-spring-security-samples/grails-spring-security-spring-boot-actuators

Let me know if I can help you in any other way.

**Comment by majaode** [comment]
I have the same issue.
I believe that the answer is not actually the same goal.
I think, @gregopet mean to secure the endpoint details, not the entire health url.
