### ISSUE TITLE
Default security headers not sent with request.

### ISSUE THREAD

**Issue by virtualdogbert** [grails-plugins/grails-spring-security-core#431]
So the default security headers are not sent with requests, and it doesn't look like there is anyway in the plugin to configure them currently.

https://docs.spring.io/spring-security/site/docs/current/reference/html/headers.html

Just doing some quick looking, it looks like this may have been added in Spring Security 3.2

**Comment by ddelponte** [comment]
Hi @virtualdogbert !  Thank-you for the bug report.

Do you recall which version of `grails` and `spring-security-core` you were using when you discovered this?

**Comment by virtualdogbert** [comment]
Just did a quick look up, and I think, at the time I think we were at Grails  3.0.9 and spring-security-core 3.0.0, we've since upgrade to 3.2.4 and 3.1.1.

**Comment by ddelponte** [comment]
Can you confirm that, since the upgrade, the default security headers are being sent with requests?
`spring-security-core` version 3.1.x utilizes `spring-security` version 4.x which should provide the desired functionality.

Thank-you for taking the time to investigate and respond. It's much appreciated :)

**Comment by virtualdogbert** [comment]
Just got back from vacation. I'll see if I can test it this week. I know as a work around we're using an interceptor to add the headers, so I'll have to refamiliarize my self with where that code is and disable it.

**Comment by virtualdogbert** [comment]
Just did a quick check and it looks like it's working.

**Comment by ddelponte** [comment]
Thank-you @virtualdogbert 🏅
