### ISSUE TITLE
Invalid 'authenticationFailureHandler' on X509AuthenticationFilter

### ISSUE THREAD

**Issue by yuri1969** [grails-plugins/grails-spring-security-core#433]
Using GSSC 3.1.1. with Grails 3.1.6. and `useX509 = true`. Server can't start due to a problem with wiring beans to SSC's `X509AuthenticationFilter`.

> Invalid property 'authenticationFailureHandler' of bean class [org.springframework.security.web.authentication.preauth.x509.X509AuthenticationFilter]: Bean property 'authenticationFailureHandler' is not writable or has an invalid setter method. 

This regression wasn't present in GSSC 3.0.4.

**Comment by ddelponte** [comment]
@yuri1969 thanks for submitting this issue 😄 

Would you be able to attach or link to a sample app that reproduces this issue? 

Thanks!

**Comment by ddelponte** [comment]
Marking this as `Cannot Reproduce` and closing.

I will be happy to reopen it if you would be so kind as to attach or link to a sample app which reproduces the problem.
