### ISSUE TITLE
Spring Security 3.1.1 does not work with Grails 3.1.9

### ISSUE THREAD

**Issue by jasenj1** [grails-plugins/grails-spring-security-core#438]
Attempted to use the Spring Security Core 3.1.1 plugin with Grails 3.1.9. Always get "Sorry, we were not able to find a user with that username and password." This is following the tutorial provided in the plugin documentation.

**Comment by burtbeckwith** [comment]
There's a small sample app in the source repo that I keep fairly current. I updated it to Grails 3.1.9 and everything worked fine. Take a look at https://github.com/grails-plugins/grails-spring-security-core/tree/master/secured and hopefully it can shed some light on what's misconfigured in your app. If you are still having problems I can take a look at your app. Can you push the code to a a GitHub repo?

**Comment by jasenj1** [comment]
Interesting. The plugin fails with a fresh app created with 'grails create-app'.
I've created a small sample application.

https://github.com/jasenj1/grails_s2_test.git
