### ISSUE TITLE
No Configuration Option for Customizing Login UI

### ISSUE THREAD

**Issue by hunterbdb** [grails-plugins/grails-spring-security-core#445]
The documentation doesn't describe any way to customize the login form, nor how to feed different kinds of auth credentials through the form to a custom AuthorizationProvider.

**Comment by burtbeckwith** [comment]
The login form is a GSP rendered for a the /login/auth controller action, so you customize it like you would for any controller in any plugin - make your own auth.gsp or copy and modify the one from the plugin and put it in your application's grails-app/views/login folder.

I have an example project at https://github.com/burtbeckwith/FunWithSpringSecurity/tree/master/hacking_newdelhi that demonstrates how to add an additional required value to use when authenticating, and that should shed some light on how to customize login in general.
