### ISSUE TITLE
sec:link tag produces incorrect URL from action/controller params

### ISSUE THREAD

**Issue by kossatzd** [grails-plugins/grails-spring-security-core#446]
I'm using Grails 3.1.9 and Spring Security Core plugin 3.1.1

I have some custom voters implemented and am having issues handling the incoming URL when using the hasAccess tag.

[In the hasAccess method](https://github.com/grails-plugins/grails-spring-security-core/blob/master/grails-app/taglib/grails/plugin/springsecurity/SecurityTagLib.groovy#L248), there is a call to create the link to pass to the webInvocationPrivilegeEvaluator but the result has 2 leading slashes.  In my voter, the incoming request has a URI of '//role/create' for example.

Instead of using base: '/', , can it be changed to use includeContext: false instead?

Thanks!

**Comment by ddelponte** [comment]
I've back-ported the the fix from master into the 3.2.x branch.
The related PR is available at https://github.com/grails-plugins/grails-spring-security-core/pull/512

This will be fixed in the next 3.2.x release ✨
