### ISSUE TITLE
In the documentation, add a link near in Getting Started and/or Tutorials to the example project

### ISSUE THREAD

**Issue by edwardotis** [grails-plugins/grails-spring-security-core#458]
Please add a link to the example app:

https://github.com/grails-plugins/grails-spring-security-core/tree/master/secured

to the docs Getting Started and/or Tutorials:
https://grails-plugins.github.io/grails-spring-security-core/v3/index.html

The tutorials won't work without the proper build.gradle dependency section.

In particular, this ehcache-core exclusion is very hard for new users to track down. The getting started docs should be very explicit about the need for this exclusion for hibernate users. It's quite frustrating for the getting started tutorial to fail with an unexpected hibernate exception.

`	compile 'org.hibernate:hibernate-ehcache', {
		exclude module: 'ehcache-core'
	}
`

**Comment by ddelponte** [comment]
I believe this will be resolved by the [PR](https://github.com/grails-plugins/grails-spring-security-core/pull/520) for issue #519

**Comment by ddelponte** [comment]
[PR 520](https://github.com/grails-plugins/grails-spring-security-core/pull/520) has been merged and I believe it resolves this PR by adding documentation that links to example apps.

 I'm closing this PR.
