### ISSUE TITLE
Warn message when booting application

### ISSUE THREAD

**Issue by jjchiw** [grails-plugins/grails-spring-security-core#459]
Hi!

I have this warn message when booting the app

```
2017-02-14 17:19:23.722  WARN --- [ost-startStop-1] o.s.b.GenericTypeAwarePropertyDescriptor : 
Invalid JavaBean property 'exceptionMappings' being accessed! Ambiguous write methods
found next to actually used 
[public void grails.plugin.springsecurity.web.authentication.AjaxAwareAuthenticationFailureHandler.setExceptionMappings(java.util.List)]: 
[public void org.springframework.security.web.authentication.ExceptionMappingAuthenticationFailureHandler.setExceptionMappings(java.util.Map)]
```

[ExceptionMappingAuthenticationFailureHandler L70](https://github.com/spring-projects/spring-security/blob/master/web/src/main/java/org/springframework/security/web/authentication/ExceptionMappingAuthenticationFailureHandler.java#L70)

[AjaxAwareAuthenticationFailureHandler L57](https://github.com/grails-plugins/grails-spring-security-core/blob/master/src/main/groovy/grails/plugin/springsecurity/web/authentication/AjaxAwareAuthenticationFailureHandler.groovy#L57)

I'm using:
```
| Grails Version: 3.2.4
| Groovy Version: 2.4.7
| JVM Version: 1.8.0_112
| spring-security-core Version: 3.1.1
```

it's not a blocking issue just a minor/little one

Thanks :)

**Comment by sdelamo** [comment]
**How to reproduce**

In a simple app such as: 

https://github.com/grails-spring-security-samples/grails-spring-security-ajax

Log with `warn` level:

`root(WARN, ['STDOUT'])`. 

When the app starts the next log entry is printed: 

`2017-04-21 15:31:13.877  WARN --- [ost-startStop-1] o.s.b.GenericTypeAwarePropertyDescriptor : Invalid JavaBean property 'exceptionMappings' being accessed! Ambiguous write methods found next to actually used [public void grails.plugin.springsecurity.web.authentication.AjaxAwareAuthenticationFailureHandler.setExceptionMappings(java.util.List)]: [public void org.springframework.security.web.authentication.ExceptionMappingAuthenticationFailureHandler.setExceptionMappings(java.util.Map)]
`

**Comment by sdelamo** [comment]
WARN log is throw because: 

`AjaxAwareAuthenticationFailureHandler' [method signature](https://github.com/grails-plugins/grails-spring-security-core/blob/master/src/main/groovy/grails/plugin/springsecurity/web/authentication/AjaxAwareAuthenticationFailureHandler.groovy#L57) is: 

`void setExceptionMappings(List<Map<String, ?>> mappings) {`

Ancestor class `ExceptionMappingAuthenticationFailureHandler` method signature is:

`public void setExceptionMappings(Map<?, ?> failureUrlMap) {`

`grails.plugin.springsecurity.failureHandler.exceptionMappings`configuration parameter [is documented as a List of Maps](https://grails-plugins.github.io/grails-spring-security-core/v3/index.html#locking). 

On solution to remove this warning entry would be to change the configuration parameter to be a map instead of a list of maps.

**Comment by ddelponte** [comment]
Closing because this was tagged as "Won't Fix" on April 21, 2017.

**Comment by ddelponte** [comment]
Reopening based on comment from virtualdogbert in slack:
Comment below:

> I'm seeing the following warning, and it's just kind of annoying, but doesn't seem to break anything:
>  ```WARN  o.s.b.GenericTypeAwarePropertyDescriptor  - Invalid JavaBean property 'exceptionMappings' being accessed! Ambiguous write methods found next to actually used [public void grails.plugin.springsecurity.web.authentication.AjaxAwareAuthenticationFailureHandler.setExceptionMappings(java.util.List)]: [public void org.springframework.security.web.authentication.ExceptionMappingAuthenticationFailureHandler.setExceptionMappings(java.util.Map)]```
> 
> So looking this up I found this issue:
> https://github.com/grails-plugins/grails-spring-security-core/issues/459
> 
> In my app I'm not setting failureHandler.exceptionMappings, so that would imply that the default in wrong. What should this be so the warning goes away?
> Also that solution should get added to the ticket, so others know what should change. Also Since the default is wrong this ticket should not be won't fix, and should be reopened in my opinion.

**Comment by jamesdh** [comment]
Correct, the default mapping is already a list:
https://github.com/grails-plugins/grails-spring-security-core/blob/a15c3d5fe3f52f7011abb71cc4ee7799c7627069/plugin/grails-app/conf/DefaultSecurityConfig.groovy#L111

**Comment by jamesdh** [comment]
It appears the only way around this warning is to change the default setter method to a different name. The Spring team had [a related issue at one point when dealing w/ multiple args](https://github.com/spring-projects/spring-framework/issues/17933) which they fixed, but for this setter w/ a matching number of args, it's warning appears to be correct. 

[This is the commit ](https://github.com/grails-plugins/grails-spring-security-core/commit/abec6fdcfe58fc529842f7ad236f5c05923d71c7)that appears to be the cause of this.
