### ISSUE TITLE
Conflict between Grails and Spring Security Plugin (v3.1.1) as of Grails >3.2.4

### ISSUE THREAD

**Issue by goedef** [grails-plugins/grails-spring-security-core#461]
Two days ago I reported an issue on grails-core. For an explanation please see: https://github.com/grails/grails-core/issues/10487

Basically I wanted to upgrade from grails 3.2.4 to 3.2.6 and could not update the UserRoles anymore (with the standard code from the Security Plugin)

I can reproduce the problem on a clean install of Grails version 3.2.6 and Spring Security Plugin 3.1.1. The problem is as follows:
When I update a user I use the following code to update the UserRole table:

    user.save flush:true
    UserRole.removeAll(user)
    for (roleId in params.list('roles')){
        Role r = Role.get(roleId)
        UserRole.create(user, r)
    }
In the UserRole domain class I use the standard code generated by the plugin.
When I update the user the UserRole table is not updated properly. I changed instance.save() to instance.save(failOnError: true) and then I get the stacktrace at the end of this message. The UserRole domain class thinks the table still holds the role I thought I removed with UserRole.removeAll(userInstance).

When I downgrade to Grails 3.2.4 everything works fine. So it seems there is a problem as of Grails version 3.2.5.

After some investigation by Graeme Rocher the conclusion was/is that the WithNewSession{} in the UserRole validator of standard code of the plugin should be removed. I think everybody will experience problems with updating UserRole after upgrading to grails >3.2.4

Graeme send me the following email text:

> As far as I can tell this is not a bug and worked before because of a bug in Grails. Previously withNewSession was not working correctly, and was re-using the existing session.
> 
> What happens is as follows:
> 
> On the line UserRole.removeAll(user) the user's roles are removed within the current transaction
> On the line UserRole.create(user, r) the UserRole is recreated, however withNewSession is used to establish of a UserRole already exists within a custom validator:
> UserRole.withNewSession {
> 	if (UserRole.exists(ur.user.id, r.id)) {
> 		return ['userRole.exists']
> 	}
> }
> The withNewSession opens a new database connection which has no visibility to the changes that were done in step 1) since the transactions are isolated. Validation therefore fails and an error is returned.
> 
> This only happens when you attempt to recreate the same UserRole when it already exists. If I remove the use of withNewSession the problem is resolved, since it using the current database connection which has visibility within the transaction.

Please advise what to do...

attached you will find a
[sec-test.zip](https://github.com/grails-plugins/grails-spring-security-core/files/790131/sec-test.zip)
 sample application

**Comment by sdelamo** [comment]
@goedef  Instead of removing all the roles granted to the user and create them again, which results in recreating roles which the users already had and thus you did not need to delete, I believe you should change your code to: 

A) remove the roles which are not present in the new roles.
B) insert the roles which the user previously did not have. 

This will be an implementation:

```
class UserRoleService {

@Transactional
    User updateUserRoles(Long userId, List<Long> newRoles, boolean flush = false) {
        def user = User.get(userId)
        if (!user) {
            return null
        }
        if (!newRoles) {
            removeAllUserRoleByUser(user, flush)
            return user
        }

        def existingRoles = findAllRoleIdsByUser(userId)

        def rolesToBeRemoved = existingRoles - newRoles

        def rolesToBeInsert = newRoles - existingRoles

        rolesToBeRemoved.each { Long roleId ->
            removeUserRoleByUserAndRole(user, Role.get(roleId), flush)
        }
        rolesToBeInsert.each { Long roleId ->
            def userRole = new UserRole(user: user, role: Role.get(roleId))
            userRole.save(flush: flush)
        }

        user
    }
    @Transactional
    boolean removeUserRoleByUserAndRole(User u, Role r, boolean flush = false) {
        if (u == null || r == null) {
            return false
        }

        int rowCount = UserRole.where { user == u && role == r }.deleteAll()

        if (flush) { UserRole.withSession { it.flush() } }

        rowCount
    }
    
    @Transactional(readOnly = true)
    List<Long> findAllRoleIdsByUser(Long userId) {
        def c = UserRole.createCriteria()
        c.list {
            projections {
                role {
                    property('id')
                }
            }
            user {
                eq('id', userId)
            }
        } as List<Long>
    }

   @Transactional
    void removeAllUserRoleByUser(User u, boolean flush = false) {
        if (u == null) {
            return
        }

        UserRole.where { user == u }.deleteAll()

        if (flush) { UserRole.withSession { it.flush() } }
    }
}
  
```

**Comment by ddelponte** [comment]
@goedef , did @sdelamo 's suggestion work for you?

**Comment by ddelponte** [comment]
Closing.  No response has been received.  I'm assuming @sdelamo 's suggestion worked
