### ISSUE TITLE
springsecurityservice injection failed on gsp

### ISSUE THREAD

**Issue by idiengaid** [grails-plugins/grails-spring-security-core#463]
Hi i'm facing a trouble when in my gsp i try to call spring security service for getting current user
    def springSecurityService = grailsApplication.classLoader.loadClass('grails.plugin.springsecurity.SpringSecurityService').newInstance()

![image](https://cloud.githubusercontent.com/assets/19474979/23564207/a8a0abae-0041-11e7-8555-7f9ce5b70e6b.png)

If someone have any idea
grails 2.4.4
spring security core 2.0.0

Regards

**Comment by idiengaid** [comment]
Hello again fixed using tag g:set instead of
def springSecurityService = grailsApplication.classLoader.loadClass('grails.plugin.springsecurity.SpringSecurityService').newInstance()


<g:set var="secuserv" bean="springSecurityService"/>

**Comment by burtbeckwith** [comment]
You shouldn't be doing work like this in a view - just pass whatever data is needed to render the output from the controller.

**Comment by idiengaid** [comment]
Yeah of course but it's just that there is a personalized field of user i initialize after login i have to use it on all view for the connected one so i put it on the main. If i try the controller every action should have the data to render and my app have already started.
Sorry for the english.
