### ISSUE TITLE
How to tie OAuth authentication with Spring Security Plugin?

### ISSUE THREAD

**Issue by Omnipresent** [grails-plugins/grails-spring-security-core#465]
I have a Grails 2.5.3 app that currently uses spring security plugin for authentication. Users login using a username/pwd.

I have updated the app now to support OAuth authentication (Using ScribeJava). Users can click a link that redirects them to OAuth providers page and upon successfully entering the credentials they are redirected back to my application. However, I have not been able to tie this functionality with spring security plugin so that when the users are redirected back to my app (after successful login from OAuth), I can actually see that they are logged in and continue to use all my spring security goodies like `<sec:ifLoggedIn>` etc..

Does anyone know of a way to do this or have an example I can take a look at?

**Comment by sdelamo** [comment]
Probably the best way to integrate OAuth is to use Spring Security Rest plugin which depends and integrates with Spring Security Core.

See: http://alvarosanchez.github.io/grails-spring-security-rest/latest/docs/#_delegating_authentication_to_oauth_providers

I am closing this issue, @Omnipresent please feel free to reopen if I did not answer your question.
