### ISSUE TITLE
Debug filter activation.

### ISSUE THREAD

**Issue by aadrian** [grails-plugins/grails-spring-security-core#467]
Please update the documentation about the debug filter (maybe even extend the ```s2-quickstart``` to add it as an option) , since what's described there: http://grails-plugins.github.io/grails-spring-security-core/v3/index.html#debug-filter doesn't seems to work for Grails 3 anymore ( Logback instead of Log4j, ```application.yml``` instead of ```Config.groovy```, etc.

Thank you.

**Comment by sdelamo** [comment]
hello @aadrian 

I have updated the docs replacing `Config.groovy` references with `application.yml` and `Log4J` with `logback`. See: 

 https://github.com/grails-plugins/grails-spring-security-core/commit/55b657caaa6efe766a08574582ab41bf7fc32791

**Comment by sdelamo** [comment]
I've added a debugging section to the docs too. 

See: 

https://github.com/grails-plugins/grails-spring-security-core/commit/1641f9f91212ccb94642efaaf6abf9fbd6e6be0d

**Comment by aadrian** [comment]
@sdelamo It looks good! Thank you.
