### ISSUE TITLE
FORWARD DispatcherType missing from springSecurityFilter

### ISSUE THREAD

**Issue by jglapa** [grails-plugins/grails-spring-security-core#472]
I've noticed that requests ending up with a `403` status code were not correctly rendering an error page.

I have a UrlMapping that says that for `403` codes a special error page should be rendered. That error page relies on securityContext and for some reason it wasn't set.

After debugging it came out that the error page was initiated with a dispatchType: FORWARD

After looking at the src of the plugin I've noticed that in this line https://github.com/grails-plugins/grails-spring-security-core/blob/7f09c528bedcf53ff9d109dad725d68a54d36a2e/src/main/groovy/grails/plugin/springsecurity/SpringSecurityCoreGrailsPlugin.groovy#L207 only 2 dispatch types are being set.

I've redefined the `springSecurityFilterChainRegistrationBean` and added the `DispatcherType.FORWARD`.

With this change everything works. 
SecurityContext is set also for error pages.

Is this a spring security plugin problem or my grails app is somehow misconfigured?

`Grails 3.2.6`
 `spring-security-plugin 3.1.1`

PS.
I'm affected by this (not sure why) https://github.com/grails-plugins/grails-spring-security-core/issues/401 and I'm using this `@EnableAutoConfiguration(exclude = [SecurityFilterAutoConfiguration])` - not sure if this is relevant here

PS.2
the issue was surfacing only in prod mode when deployed to Tomcat

**Comment by ddelponte** [comment]
@jglapa, thank-you for submitting this issue!

Is this still not working for you?  

If so, would you be so kind as to attach (or link to) a sample app which reproduces the problem?  
Thanks!

**Comment by ddelponte** [comment]
Marking this as `Cannot Reproduce` and closing.

I will be happy to reopen it if you would be so kind as to attach or link to a sample app which reproduces the problem.

**Comment by jglapa** [comment]
Hi @ddelponte sorry for not getting back to you. 
I tried reproducing this last time you commented  on a small app but failed... I've also forgot to mention that in June...
My app has 4 years of grails development with numerous grails upgrades and alterations/
It might be that something in my app is affecting how the spring security behaves. I wasn't able to narrow that down. I think it's fine to close this. The issue itself can be a hint for somebody else struggling with something similar.

**Comment by ddelponte** [comment]
Thank-you for following up!  👍
