### ISSUE TITLE
Role_Anonymous is being set

### ISSUE THREAD

**Issue by sonikas** [grails-plugins/grails-spring-security-core#474]
OS -Windows 10
Grails 2.4.4
Jboss 7.0 EAP

When I try to login application, it goes Username and Password Authentication token, and then AjaxAwareAuthenticationSuccessHandler. Here the roles are correctly being set. After this somehow it enters in GrailsAnonymousUser and set the role as Anonymous user.
Secondly some observations are :-In webauthenticationdetails file session id is coming as null . and PBOX00354: Setting security roles ThreadLocal: null also gets printed in console.
Explored multile options but did not worked. Kindly suggest

**Comment by sdelamo** [comment]
I think the Anonymous behaviour you are describing is documented in the docs: 

https://grails-plugins.github.io/grails-spring-security-core/latest/#anonymous-authentication
