### ISSUE TITLE
Update the SecurityTagLib to support namespace parameter inside hasAccess

### ISSUE THREAD

**Issue by joemccall86** [grails-plugins/grails-spring-security-core#486]
I want to use a rule like:

```
<sec:access controller="user" namespace="admin" action="index">...</sec:access>
```

but there's no logic to check for the namespace parameter. See SecurityTagLib.groovy:246:

```
			else {
				String action = attrs.remove('action')
				url = g.createLink(controller: controller, action: action, base: '/')
			}
```

I think it should take into account the namespace parameter. I don't mind issuing a PR for this myself, but I wanted to capture it in a ticket first.

**Comment by sdelamo** [comment]
A PR would be great. I will review it and merge it
