### ISSUE TITLE
Class locations changed for Grails 3.3.0.M1

### ISSUE THREAD

**Issue by erichelgeson** [grails-plugins/grails-spring-security-core#488]
```
import org.springframework.boot.context.embedded.FilterRegistrationBean
import org.springframework.boot.context.embedded.ServletListenerRegistrationBean
```

Do not exist anymore, now under

```
package org.springframework.boot.web.servlet;
```

**Comment by nagysz** [comment]
Hit the same problem this afternoon. Took a while to figure it out... is there any workaround, or is the plugin currently incompatible with Grails 3.3.0.M1?

**Comment by sdelamo** [comment]
@nagysz I am working to release a version of the plugin compatible to 3.3.0.M1

**Comment by nagysz** [comment]
@sdelamo Awsome, keep up the good work!

**Comment by sdelamo** [comment]
I have released a version of Spring Security Core compatible with Grails 3.3.0.M1. It is SSC version 3.2.0.M1
