### ISSUE TITLE
loadSecondaryConfig inside doWithApplicationContext() breaks property placeholder syntax for getProperty()

### ISSUE THREAD

**Issue by joemccall86** [grails-plugins/grails-spring-security-core#492]
Sample Application
===
See sample application here: https://github.com/joemccall86/config-parse-test

Grails 3.2.9
Spring Security Core Plugin 3.1.2

I have a simple `DefaultSecondaryConfig.groovy` whose contents don't seem to matter to reproduce this bug. I also have a `SecondaryConfigLoader.groovy` bean defined in `src/main/groovy` and injected in `resources.groovy`, to simulate a plugin lifecycle action for demonstration purposes.

`ReadConfigService.groovy` is a grails service that reads configuration using the map-navigation syntax `co.myApp.value`, as well as the preferred `getProperty` syntax `co.getProperty('myApp.value')`. Its service method asserts that both read values are equal. 

`application.yml` defines a property `myApp.value: '${MY_APP_VALUE:foo}'` that should evaluate to `foo` when `MY_APP_VALUE` is not defined (the default case in the sample application).

I call the service method inside `BootStrap.groovy`, so the application only runs if the assertion is true.

Expected Behavior
===
Both property values are equal, regardless of where `SpringSecurityUtils.loadSecondaryConfig` is called in the application lifecycle. The application runs without any error.

Actual Behavior
===
The assertion fails inside the service method:
```
org.codehaus.groovy.runtime.powerassert.PowerAssertionError: assert value1 == value2
       |         |
       |         foo
       ${MY_APP_VALUE:foo}
```

This can be tracked down to calling `SpringSecurityUtils.loadSecondaryConfig` inside `doWithApplicationContext`. Commenting out that line makes the assertion pass.

Workaround
===
Use the less-efficient map-navigation syntax for parsing configuration

**Comment by ddelponte** [comment]
I have successfully reproduced this issue using:

Grails 3.3.6
grails-spring-security-core: 3.2.2

Sample app: https://github.com/ddelponte/grails-spring-security-core-issue492

**Comment by ddelponte** [comment]
Everything works as expected when the secondary configuration is loaded in the `onStartup` initialization hook.

Please an example of it working at https://github.com/ddelponte/grails-spring-security-core-issue492

**Comment by ddelponte** [comment]
This may be related to https://github.com/bluesliverx/grails-spring-security-oauth2-provider/issues/138

**Comment by joemccall86** [comment]
It's been a while, but yes I believe they're essentially the same bug. I filed this issue once I was able to narrow down the behaviors a bit. Since groovy map syntax worked fine as a workaround I haven't really looked further into it.

**Comment by ddelponte** [comment]
@joemccall86 

FYI: `getProperty()` works the same as the groovy map syntax if the secondary config is loaded from within the `onStartup` initialization hook.

If this is expected behavior (I'm not sure yet), I'll likely close this issue. ✨

**Comment by joemccall86** [comment]
I would think that the bug would lie in the fact that I can break my properties object (or more specifically my ability to use getProperty() on it) simply by loading a secondary config outside of onStartup() (e.g., a doWithApplicationContext() block.)

If you ask me it would either need to be fully supported being called from anywhere or throw a hard failure if called after onStartup() is done.

**Comment by ddelponte** [comment]
It looks like the bug resides in grails core.

I've created a new issue in grails-core to fix the bug:  https://github.com/grails/grails-core/issues/11042

I'm closing this ticket
