### ISSUE TITLE
Grails 3.2.9, spring-security-core:3.1.2 plugin not honoring BootStrap.groovy 

### ISSUE THREAD

**Issue by dorisviv** [grails-plugins/grails-spring-security-core#493]
I made a mistake and added the following to BootStrap.groovy:

`new RequestMap(url: '/', configAttribute: ("ADMIN_GROUP, SUPER_USER_GROUP")).save()`

This, on Grails startup, predictably, created the error:

Error parsing expression 'ADMIN_GROUP, SUPER_USER_GROUP': EL1041E: After parsing a valid expression, there is still more data in the expression: 'comma(,)'

Reading the doc, I realized the configAttribute needs to be prefaced with ROLE_. So I changed it to:

`new RequestMap(url: '/', configAttribute: 'ROLE_ADMIN,ROLE_SUPER_USER').save()`

I got the same parsing error on Grails startup.

I then REMOVED ALL CODE from BootStrap.init, and STILL GET the parsing error on startup.

I created a small project and was not able to reproduce the error. Unfortunately I cannot upload a live project for trouble-shooting.

I then removed all spring security from my project and it started up. I stopped the project and added      compile "org.grails.plugins:spring-security-core:3.1.2" to build.gradle. The error reapearred on startup. I added springSecurityService.clearCachedRequestmaps() as the only line to BootStrap.init.  But, RequestmapFilterInvocationDefinition.loadRequestmaps() is not honoring the BootStrap changes.  SpringSecurityService.clearCachedRequestmaps() seems to be ineffective. There seems to be no objectDefinitionSource?.reset() method? I'm assuming there is some kind of caching going on, but where do I clear it manually? Project is dead in the water.

**Comment by dorisviv** [comment]
configAttribute: ("ADMIN_GROUP, SUPER_USER_GROUP") had made it into the database. ReflectionUtils.loadAllRequestmaps()stumbled over it on Grails startup. Deleted that row from the database, works now.

**Comment by sdelamo** [comment]
sorry @dorisviv but I don't understand the issue. I am going to close it as you seen to have found the solution. If you consider there is is still open, I will appreciate if you could link to repository example.
