### ISSUE TITLE
spring-security-core:3.1.2 and MongoDB 6.1.2

### ISSUE THREAD

**Issue by barcelona23** [grails-plugins/grails-spring-security-core#496]
Hi,
I have been using ssc 3.1.1 a while. I decided to update to 3.1.2, but I found some problems working together with mongodb database.

Since the password encoding is not directly in domain class
<img width="694" alt="screen shot 2017-06-07 at 9 26 32 pm" src="https://user-images.githubusercontent.com/221474/26911116-89eed136-4bc8-11e7-8a24-b98d96df90f1.png">

I'm using mongoDB as primary database, I commented all hibernate plugins.
<img width="839" alt="screen shot 2017-06-07 at 9 23 34 pm" src="https://user-images.githubusercontent.com/221474/26911140-b6e51aec-4bc8-11e7-8e60-fdd4c5a1e550.png">

This is the error.
<img width="567" alt="screen shot 2017-06-07 at 9 22 57 pm" src="https://user-images.githubusercontent.com/221474/26911163-e0606b4c-4bc8-11e7-9000-4844a24c302d.png">

Is it missing something? I know the bean name is 'hibernateDatastore', but I did not find any documentation relate about mongodb and spring security.

Should I use the password encoding directly in domain class?

<img width="924" alt="screen shot 2017-06-07 at 9 37 09 pm" src="https://user-images.githubusercontent.com/221474/26911287-7dc78d70-4bc9-11e7-9514-94fe11a92f17.png">

<img width="549" alt="screen shot 2017-06-07 at 9 24 30 pm" src="https://user-images.githubusercontent.com/221474/26911219-24a12c4c-4bc9-11e7-8aae-ec79748f3743.png">
<img width="495" alt="screen shot 2017-06-07 at 9 25 45 pm" src="https://user-images.githubusercontent.com/221474/26911220-24a624e0-4bc9-11e7-9338-f5455c2f8bd6.png">
<img width="258" alt="screen shot 2017-06-07 at 9 25 59 pm" src="https://user-images.githubusercontent.com/221474/26911221-24a99ff8-4bc9-11e7-8624-07c451919acc.png">

**Comment by barcelona23** [comment]
https://stackoverflow.com/q/44426277/624921

**Comment by sdelamo** [comment]
I have created  a simple app with Spring Security Core and MongoDB: 

https://github.com/grails-spring-security-samples/grails-ssc-mongodb

You would need to replace in `grails-app/conf/spring/resources.groovy`

`userPasswordEncoderListener(UserPasswordEncoderListener, ref('hibernateDatastore'))`

with:

`userPasswordEncoderListener(UserPasswordEncoderListener, ref('mongoDatastore'))`
