### ISSUE TITLE
Consider lowering bcrypt values for faster for tests

### ISSUE THREAD

**Issue by erichelgeson** [grails-plugins/grails-spring-security-core#498]
As pointed out here http://blog.ackx.net/speed-up-grails-tests-spring-security-bcrypt.html you can gain quite a bit of speed in your tests by lowering the value of bcrypt when the grails env is test. It might be valuable to do this by default in the plugin.

**Comment by YouriAckx** [comment]
Thanks for opening this issue, I wasn't sure this tracker was actively monitored.

The tl;dr version is:

```
application.groovy

if (Environment.current == Environment.TEST) {
    grails.plugin.springsecurity.password.bcrypt.logrounds = 4
    grails.plugin.springsecurity.password.hash.iterations = 1
}
```

Practically, we reduced our execution time by 2-3 under real conditions, and by 10 under specific conditions for reproduction purpose.

Extra: could the `bcrypt` be bypassed altogether in favor of a dummy algorithm?

**Comment by ilopmar** [comment]
Actually you can use another algorithm, for example MD5. Just add to your `Config.groovy` or `application.groovy`:

```
grails.plugin.springsecurity.password.algorithm = 'MD5'
```

**Comment by YouriAckx** [comment]
Not familiar with the plugin architecture, but if we have different default values test/other, and the user explicitly set the bcrypt parameters, won't they be overridden for all environments test/other as a consequence?

Eg the new defaults would be: `4/1` (tests) and `10/1000` (other)

If want to increase the strength and do the following:

```
    grails.plugin.springsecurity.password.bcrypt.logrounds = 20
    grails.plugin.springsecurity.password.hash.iterations = 2000
```

then I'd get `20/2000` (tests) and `20/2000` (other), and tests would be slower as a side effect.

One might argue that the documentation shall point out that if the user overrides the values, they would be wise to have an `if/else` on the `Environment` and set them accordingly, but this can be easily overlooked, leading to "why are my tests suddenly so slow" moments.

@edarchis suggests a clear warning when running the tests with values other than `4/1`.

**Comment by sdelamo** [comment]
@YouriAckx thanks for your blog post. It is a good tip indeed. 

It is a trade-off though. On the one hand you increase speed, on the other hand your integration tests will not match your production environment. 

What are you guys suggesting to resolve this issue? Adding to the documentation that it is possible to have a different password algorithm or configuration depending on the environment and those changes will help you to speed up your integration tests?

**Comment by YouriAckx** [comment]
@sdelamo A clear tip in the documentation could do the trick, without changing the plugin implementation and, most of all, without introducing magic that could backfire or at the very least change the current behavior.

I cannot think of a practical use case where this would be an issue but it is safe to assume that it could impact someone somewhere.

**Comment by erichelgeson** [comment]
This just changes how fast the bcrypt function happens, so no functional changes to your test environment. If you're relying on the computed bcrypt values in your tests, I'd like to know what use case that is.

This optimization has been in rails for quite a while https://github.com/rails/rails/commit/06faa6da808ef9e98455c35aefd4a4112c811c8f and just seems like a sane optimization. 

I'd suggest the plugin detect when it's in test environment and set those properties lower.

**Comment by YouriAckx** [comment]
Very first draft of this optimization [in a branch](https://github.com/YouriAckx/grails-spring-security-core/commit/38a31b0206dff491425454d85c324dc54b5cf8a1), as a basis for discussion.

* Is the wording ok?
* I did not find any inspiration in the existing unit/integration/functional tests to add test coverage. Would a unit test mocking `Environment` do, knowing that `DefaultSecurityConfig.groovy` is a resource in `conf` rather than a source class? I'm not aware of the project testing guidelines or requirements.
