### ISSUE TITLE
Documentation links for grails 2.x is broken

### ISSUE THREAD

**Issue by snimavat** [grails-plugins/grails-spring-security-core#499]
Plugin docs for grails 2.x version is no longer available, links are broken
see http://grails-plugins.github.io/grails-spring-security-core/2.0.x/index.html

Pl have it fixed, as many people will still need this.

Thanks

**Comment by erichelgeson** [comment]
http://grails-plugins.github.io/grails-spring-security-core/v2/index.html fyi incase anyone stumbles across this message.

**Comment by sdelamo** [comment]
Links are fixed. Thanks for reporting.
