### ISSUE TITLE
login/auth not found

### ISSUE THREAD

**Issue by artemik** [grails-plugins/grails-spring-security-core#501]
Grails 3.2.11.
Default rest profile app. Default security core plugin s2-quickstart layout.

Trying access localhost:8080 redirects to /login/auth, but error message not found. Debugging, the flow doesn't step into LoginController.
___
Update 1.
Adding this:

> "/$controller/$action?/$id?(.$format)?" {
>             constraints {
>                 // apply constraints here
>             }
> }

to UrlMappings makes Grails now see and step into LoginController. Why wasn't it there by default? But now it's 500 error /login/auth view not found. Looks like Grails can't find view from the plugin.

But the mapping above should anyway be added to the documentation and stated it's required for the security plugin to work.

**Comment by sdelamo** [comment]
Could you upload a repository to github and share it here with me so that I could take a look

**Comment by artemik** [comment]
https://github.com/artemik/grails-security-core-issue-test

Steps:
1. grails create-app --profile=rest-api
2. add `compile 'org.grails.plugins:spring-security-core:3.1.2'` to build dependencies
3. grails s2-quickstart --uiOnly

Even without step 3 the web profile works ok - redirects me to /login/auth and shows login form, although without styles, due to skipped step 3.

**Comment by sdelamo** [comment]
> Although it's rest-api profile I think views should work. Being rest-api, the application can still have 
> actuator UI or some other administrative UIs which should anyway work.

If you want to mix JSON and HTML views, you should use the `web` profile. 

Or create a mutli-project build with two apps where one app is the administrative stuff which uses the `web` profile and the other is the api which uses the `rest-api` profile

**Comment by sdelamo** [comment]
We have a Guide which shows how to use Spring Security Core, Spring Security REST in the same app:  

http://guides.grails.org/grails-test-security/guide/index.html

**Comment by gantaa** [comment]
Thanks @artemik for pointing out the basic necessary URLMapping for fixing 404 requests to the auth.gsp page.  I agree this should be called out in the Grails Spring Security plugin documentation, would've saved me time, as my entire API is built RESTful and omits gsp views, so we never had that required UrlMapping
