### ISSUE TITLE
What is "URL Properties"?

### ISSUE THREAD

**Issue by artemik** [grails-plugins/grails-spring-security-core#502]
In the documentation, there is a `13. URL Properties` section. 
Why is it called URL properties? Does it mean I can set them per specific URLs? If yes, then how? A confusing name.

What namespace do they belong to? From Google I found that the prefix for all those properties should be `grails.plugin.springsecurity`, please add this to the docs.

**Comment by sdelamo** [comment]
The name `URL properties` refers to the fact that they are a set of properites which allows you to change things such as URL path or parameters name. 

For example, 

`auth.loginFormUrl`is the default URL path to the login page with a default value of `/login/auth`

If you want your app to have a login path such as `/signin` you will need to setup that property to that value. 

That said, pull-requests with improvements to the copy of the documentation are welcome. Personally, I think it is an OK section name.
