### ISSUE TITLE
s2-quickstart isn't complete.

### ISSUE THREAD

**Issue by limhee** [grails-plugins/grails-spring-security-core#510]
After I run s2-quickstart at cmd and trying to create User, Role.  

On the domain class for User, Role, UserRole

```
String toString(){
            username
        }

	User(String username, String password) {
		this()
		this.username = username
		this.password = password
	}
```
This is missing for User domain 

`Role(String authority) {
		this()
		this.authority = authority
	}
        String toString(){
            authority
        }`

is missing for Role domain

`UserRole(User u, Role r) {
		this()
		user = u
		role = r
	}`

Is missing on UserRole domain

**Comment by sdelamo** [comment]
Those constructors were removed "removed parameterized constructors" commit:
 
in https://github.com/grails-plugins/grails-spring-security-core/commit/07e1287e61b72d0ebf7221557f7742cfcbdd5b8e#diff-0fc0304fc55403c8ff3419dfcd8bd5c4

and "updated the docs to be consistent with how the domain classes are gen..."

https://github.com/grails-plugins/grails-spring-security-core/commit/2a70dd97b577e265f85c23156549bda0cddd5464
