### ISSUE TITLE
Create a new sample section in the docs with links to examples

### ISSUE THREAD

**Issue by ddelponte** [grails-plugins/grails-spring-security-core#519]
Example apps are available at github.com/grails-spring-security-samples

Create a new sample section towards the end of the documentations near the tutorials section

**Comment by ddelponte** [comment]
This is a duplicate of https://github.com/grails-plugins/grails-spring-security-core/issues/458

**Comment by sdelamo** [comment]
This is already visible in the snapshot docs. https://grails-plugins.github.io/grails-spring-security-core/snapshot/#examples

thanks @ddelponte
