### ISSUE TITLE
Infinite loop login page when securityConfigType = 'Requestmap'

### ISSUE THREAD

**Issue by piyawatd** [grails-plugins/grails-spring-security-core#535]
My project can't load login page.Browser alert

> redirecting the request for this address in a way that will never complete

grails version 3.3.3
postgresql 10

build.gradle

`
compile "org.grails.plugins:hibernate5"

compile "org.hibernate:hibernate-core:5.1.5.Final"

compile "org.grails.plugins:spring-security-core:3.2.1"

runtime "org.postgresql:postgresql:42.1.4"
`

application.groovy
`
grails.plugin.springsecurity.userLookup.userDomainClassName = 'hr.Users'
grails.plugin.springsecurity.userLookup.authorityJoinClassName = 'hr.UsersRole'
grails.plugin.springsecurity.authority.className = 'hr.Role'
grails.plugin.springsecurity.requestMap.className = 'hr.Requestmap'
grails.plugin.springsecurity.securityConfigType = 'Requestmap'
`

code in bootstrap
`
def springSecurityService

    def init = { servletContext ->
        for (String url in [
                '/', '/error', '/index', '/index.gsp', '/**/favicon.ico', '/shutdown',
                '/assets/**', '/**/js/**', '/**/css/**', '/**/images/**',
                '/login', '/login.*', '/login/*','/login/auth',
                '/logout', '/logout.*', '/logout/*']) {
            new Requestmap(url: url, configAttribute: 'permitAll').save()
        }
        new Requestmap(url: '/user/profile/**',    configAttribute: 'ROLE_USER').save()
        new Requestmap(url: '/admin/**',      configAttribute: 'ROLE_ADMIN').save()
        new Requestmap(url: '/admin/role/**', configAttribute: 'ROLE_SUPERVISOR').save()
        new Requestmap(url: '/admin/user/**',
                configAttribute: 'ROLE_ADMIN,ROLE_SUPERVISOR').save()
        new Requestmap(url: '/login/impersonate',
                configAttribute: 'ROLE_SWITCH_USER,isFullyAuthenticated()').save()
        springSecurityService.clearCachedRequestmaps()
    }
`

when in run application it loop redirect 127.0.0.1:8080/login/auth
if I config application.groovy use InterceptUrlMap 
`
grails.plugin.springsecurity.securityConfigType = 'InterceptUrlMap'
`
it work.

**Comment by piyawatd** [comment]
I resolve this issue.I forgot flush:true in save method.

**Comment by sdelamo** [comment]
You should move those saves to a service and annotate with @transactional instead
