### ISSUE TITLE
staticRules doesn't work with Grails Melody plugin

### ISSUE THREAD

**Issue by kuceram** [grails-plugins/grails-spring-security-core#537]
Despite the fact that I restrict `/monitoring` url with static rules, I can still access it even not authenticated.

Grails: 3.3.2
Grails Melody Plugin: 1.70.0
Grails Spring Security: 3.2.0

```
grails.plugin.springsecurity.controllerAnnotations.staticRules = [
    [pattern: '/monitoring',        access: ['ROLE_BACKEND_ADMIN']]
]
```

Reference issue in Grails Melody plugin https://github.com/javamelody/grails-melody-plugin/issues/38

**Comment by kuceram** [comment]
Interestingly enough, it seems that it doesn't work with Spring Actuators as well, i.e. endpoint /health is accessible even if I restrict it with `[pattern: '/health', access: ['ROLE_BACKEND_ADMIN']]` and endpoint /metrics is not accessible with configuration `[pattern: '/metrics', access: ['permitAll']]`.

**Comment by sergiomichels** [comment]
Replied at https://github.com/javamelody/grails-melody-plugin/issues/38, this is working in my example.

**Comment by alvarezlean** [comment]
The problem may be elsewhere. When the access rules are defined in the controllers, it is possible that there is an error, for example, an extra comma, and that means that the authentication rules are not finished loading.
To be sure, you should look at the log if there is a WARN that has not been able to parse the rules.

**Comment by kuceram** [comment]
Thanks @alvarezlean for your suggestion. The problem you describes was not the issue however it force me to switch on logging which led to the core problem discovery. See details in my response here https://github.com/javamelody/grails-melody-plugin/issues/38.
