### ISSUE TITLE
The return of RenderConverterTrait NoClassDefFoundError

### ISSUE THREAD

**Issue by claudiocarcaci** [grails-plugins/grails-spring-security-core#538]
Hi, I'm struggling on this issue.

I have a fresh Grails 3.2.0 environment.
My build.gradle is attached. In particular I have the following lines:

```
compile "org.grails.plugins:spring-security-core:3.1.2"
compile "org.grails.plugins:spring-security-rest:2.0.0.RC1"
```

When I try to run my application I receive the stacktrace attached which says:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'grailsApplicationPostProcessor' defined in com.motork.Application: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [grails.boot.config.GrailsApplicationPostProcessor]: Factory method 'grailsApplicationPostProcessor' threw exception; nested exception is grails.plugins.exceptions.PluginException: Failed to initialize class [grails.plugin.springsecurity.rest.RestOauthController] from plugin [springSecurityRest] : org/grails/compiler/web/converters/RenderConverterTrait
...
Caused by: java.lang.ClassNotFoundException: org.grails.compiler.web.converters.RenderConverterTrait
```

I use the spring-security-core:3.2.1 as suggested here https://github.com/grails-plugins/grails-spring-security-core/issues/495
But it doesn't work

I use:
Ubuntu 16.04 LTS
Java 1.8.0_31
Grails 3.2.0

[build.gradle.txt](https://github.com/grails-plugins/grails-spring-security-core/files/1884407/build.gradle.txt)
[Stacktrace.txt](https://github.com/grails-plugins/grails-spring-security-core/files/1884374/Stacktrace.txt)

**Comment by ddelponte** [comment]
Please note, as stated in the docs, s`pring-security-core` 3.2.0.M1 is only compatible with 3.3.x or higher.

Previous Grails 3 versions (3.0.x, 3.1.x and 3.2.x) should use `spring-security-core` 3.1.2.

Are you able to attach an example app that reproduces the problem?

**Comment by claudiocarcaci** [comment]
Hi @ddelponte thenk you for your response.

As I stated in my first comment I already use the spring-security-core:3.1.2
I have created a repository which reproduces the error, here it is: https://github.com/claudiocarcaci/issue538

Thank you very much

**Comment by claudiocarcaci** [comment]
It works!

I'll wait for a feedback on the other issue for a stable version of library.
Thank you very much.
