### ISSUE TITLE
sec.access taglib is not resolving correctly on a .war deployed on tomcat 

### ISSUE THREAD

**Issue by xavier-gallofre** [grails-plugins/grails-spring-security-core#540]
I've reproduced the issue in the repository https://github.com/xavier-gallofre/sec-access-issue

**Versions and Configs**
    Tomcat: 8.5.30
    Grails: 3.3.5
    Spring-Security: 3.2.1

When I deploy a .war (generated with `./gradlew dev war`) none of sec.access taglibs are working, denying access in all cases. The same taglibs are working perfectly when I run the application with bootRun.

Spring Security is working correctly when I try to access some page secured, so the only problem is to check if I have access from a .gsp to some controller or action.

For example,

Home controller is secured with `ROLE_POLICE` and hello action is secured with `ROLE_DETECTIVE`. If you're logged with `sherlock` user it's possible to access by url to `/home/hello` but `<sec:access controller='home' action='hello'> ... </sec:access>` is resolving that you're not allowed to see it.

**Comment by jmiguelr** [comment]
Hi Dean, thank you.  No, I've deployed a _sec.war_  file. I think I see your point, I'll try to test it.   Obviously, when it's executed with bootRun it is.

**Comment by jmiguelr** [comment]
Hi @ddelponte .  I can confirm you if we deploy the war as ROOT.war on tomcat8 it works as expected.

**Comment by jmiguelr** [comment]
Hi Dean, and thank you for your reply.  I cannot think force to deploy on root context as a real solution. Usually there are more than one application per server so they need to have their own context. 

@xavier-gallofre told me this worked on previous releases so maybe (I'll try tomorrow) check for differences on AbstractFilterInvocationDefinition class may help (if I'm right, perhaps I'm not). 

Please, do not close the issue, we think it cannot be considered as solved.

**Comment by xavier-gallofre** [comment]
Hi Dean, I've tried to set that configuration (contextPath and context-path just in case) and it's not working.

Anyway, I'm not sure that change some config could be a solution to this problem.
Is not a problem if that taglib `<sec:access>` has stopped working because is not able to resolve context once deployed? Couldn't be a problem in any other case with context involved?

**Comment by ddelponte** [comment]
@xavier-gallofre , I have successfully resolved this issue by adding the following two lines to `/grails-app/conf/application.yml`:

```
server:
  contextPath: '/@info.app.name@-@info.app.version@'
```

When the war file is generated, the above config will be set using the info from `build.gradle` and `gradle.properties`.  Read more about it at http://grailsblog.objectcomputing.com/posts/2017/04/02/add-build-info-to-your-project.html .  For me, when run locally, it was set to `/sec-access-issue-0.1`.

Of course, you can always hard code your context path as well.  The point being that it should coincide with the root of your deployed app.

I then deployed to war to tomcat and confirmed it worked as expected.

Here's a video demoing it working on tomcat: https://drive.google.com/file/d/18Z3uJLnzxvJDAZp5PWbOEUVHOoj289Uc/view

Please let me know if you have any questions and if it is okay to close this ticket.

**Comment by ddelponte** [comment]
@xavier-gallofre , I believe the following PR is what broke link generation on tomcat for your specified case:

https://github.com/grails-plugins/grails-spring-security-core/pull/487/files

**Comment by jmiguelr** [comment]
Hello @ddelponte and thank you for your efforts.  Regarding the proposed solution (adding the `contextPath: '/@info.app.name@-@info.app.version@'` line, as far as I understand that would mean the context path is fixed at compilation time, isn't it?.  If so, I don't think it's a good solution althought it could work as temporal workaround. Operations people or customers should be able to deploy it with the name they want. I know, they could do a mapping job on Apache/nginx, but it's not and optimal solution. 

I thank you've keep searching for a better solution. I'm not sure if the commit you point is the one that should be fixed, I'm not sure if I'll be able to take a look on next week, maybe @xavier-gallofre could rollback it on a local copy and try it.  What is sure is that it worked on previous versiones (maybe it doesn't supports all attributes, but those supported... they worked :-))

Thank you again for your help and support.

**Comment by ddelponte** [comment]
>adding the contextPath: '/@info.app.name@-@info.app.version@' line, as far as I understand that would mean the context path is fixed at compilation time, isn't it?

Yes, you are correct.  

You also have the ability to place the configuration in a file external to your application.

More info is available at:
https://docs.grails.org/latest/guide/conf.html#ymlOptions
and
https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-application-property-files

**Comment by ddelponte** [comment]
Another option would be to set the `server.contextPath` dynamically in `application.groovy` using an external config file that specifies the `server.contextPath`

- https://stackoverflow.com/questions/35793047/grails-3-change-contextpath-dynamically-servletcontext
- http://docs.grails.org/latest/guide/conf.html#externalLoggingConfiguration
- https://plugins.grails.org/plugin/grails/external-config
- http://mrhaki.blogspot.com/2015/09/grails-goodness-using-external.html

**Comment by ddelponte** [comment]
A fix has been implemented and a PR created at https://github.com/grails-plugins/grails-spring-security-core/pull/551  ✨

**Comment by sdelamo** [comment]
Thanks to @xavier-gallofre @jmiguelr  for submitting the issue and thanks to @ddelponte  for fixing it. Version 3.2.2 of the plugin contains the fix. I have reproduced with the sample repository that the issue is fixed. Please, reopen if you find any issues with the fix.
