### ISSUE TITLE
SessionAuthenticationException is not handled in `LoginController.authfail`

### ISSUE THREAD

**Issue by mkobel** [grails-plugins/grails-spring-security-core#541]
When I configure spring security to have one session per principal, then the exception during a second login is not handled appropriate.

Config:
```
concurrentSessionControlAuthenticationStrategy(ConcurrentSessionControlAuthenticationStrategy, ref('sessionRegistry')) {
        exceptionIfMaximumExceeded = true
        maximumSessions = 1
    }
```

Exception:
```
org.springframework.security.web.authentication.session.SessionAuthenticationException: Maximum sessions of 1 for this principal exceeded
```

Expectation:

I expect the exception type `SessionAuthenticationException` is handled as the other types with a specific error message.

**Comment by ddelponte** [comment]
@mkobel which version of grails and the grails-spring-security-core plugin are you using?

**Comment by mkobel** [comment]
@ddelponte Grails 3.3.5 and grails-spring-security-core 3.2.1

**Comment by ddelponte** [comment]
I have created PR 544 to address this issue

**Comment by mkobel** [comment]
@ddelponte Looks good for me; I checked the usage of SessionAuthenticationException in spring-security-web again to see of other messages could be appropriate too and this case was the only one I found.
