### ISSUE TITLE
Request mapping not working in desired way.

### ISSUE THREAD

**Issue by vinaykr91** [grails-plugins/grails-spring-security-core#543]
I have posted a question in stackoverflow. Would be grateful if anyone could help me out.

https://stackoverflow.com/questions/50511756/requestmap-not-working-in-grails-as-expected

Grails version 2.3.4 Spring security plugin : compile ":spring-security-core:2.0-RC2"

**Comment by ddelponte** [comment]
@vinaykr91 , I believe you would need to define all Roles which may access the URL.

For example:
```
new Requestmap(url: '/admin/user/**', configAttribute: 'ROLE_ADMIN,ROLE_SUPERVISOR').save()
```
You may read more about it at http://grails-plugins.github.io/grails-spring-security-core/2.0.x/guide/requestMappings.html#requestmapInstances

**Comment by vinaykr91** [comment]
Can you please explain why `/**` given for `ROLE_ADMIN` is not working?

If `ROLE_ADMIN`  has `/**` and `ROLE_TEST` has ` /customer/**` then both admin and test user should be able to access customer page right?

**Comment by ddelponte** [comment]
`/**` for `ROLE_ADMIN` is not working the way you expect it to because the plugin calculates the most specific rule that applies to the current request.

`/customer/**` is more specific than `/**` so the associated role of ` ROLE_TEST` is applied.

**Comment by vinaykr91** [comment]
In Bootstrap.groovy, I am giving /** to admin. Before giving  /customer/** to test user , admin can access all pages (including customer). When I add a new request map for test user with  /customer/**, only test user can access it and not admin

**Comment by vinaykr91** [comment]
> because the plugin calculates the most specific rule that applies to the current request.

is there anything that I can do to override this?

**Comment by ddelponte** [comment]
> In Bootstrap.groovy, I am giving /** to admin. Before giving /customer/** to test user

When working with `RequestMaps`, the order in which these are created is irrelevant.  What's important is the specificity of the rule.

The easiest solution, and my recommendation to you, is use `Requestmap` as it was designed.  This means, when overriding general rules with more specific ones, all roles which are granted access to the more specific rule must be defined.

If you wish to modify the way rules are applied, you will need to modify the plugin and publish locally for your use.

Another approach to take would be to think about how users will be accessing your application, then create groups with roles to accommodate the access.  This will allow you to specify one group in place of many roles.

**Comment by vinaykr91** [comment]
> When working with RequestMaps, the order in which these are created is irrelevant. What's important is the specificity of the rule.

The easiest solution, and my recommendation to you, is use Requestmap as it was designed. This means, when overriding general rules with more specific ones, all roles which are granted access to the more specific rule must be defined.

If you wish to modify the way rules are applied, you will need to modify the plugin and publish locally for your use.

Agreed. I had not understood how this feature was intended to work . Thanks for clearing it up.

> Another approach to take would be to think about how users will be accessing your application, then create groups with roles to accommodate the access
Is there any built in feature in the plugin like creating groups with roles?  I did not find it iin the documentation.

**Comment by ddelponte** [comment]
Here's some documentation on groups.  Hope this helps!

https://grails-plugins.github.io/grails-spring-security-core/3.2.x/index.html#authorityGroupClass

**Comment by vinaykr91** [comment]
Thank you. This has been most helpful.

**Comment by thanneeruvenu** [comment]
springSecurityService.clearCachedRequestmaps() has to reset request map(database table), but it is not happening on when we have two different servers on different nodes are pointed on the same database.
it took some time to refresh the dynamic intercept request map.
