### ISSUE TITLE
Create an issue template similar to what is used in the grails-data-mapping plugin

### ISSUE THREAD

**Issue by ddelponte** [grails-plugins/grails-spring-security-core#546]
This will be great for prompting users to supply the information required to reproduce and fix the issue.

Example issue template: https://github.com/grails/grails-data-mapping/blob/master/ISSUE_TEMPLATE.md

**Comment by sdelamo** [comment]
Closed by : https://github.com/grails-plugins/grails-spring-security-core/commit/397ceda47a88d0d5aa81c758806a50bcd5fc8c17
