### ISSUE TITLE
Fix broken integration tests

### ISSUE THREAD

**Issue by ddelponte** [grails-plugins/grails-spring-security-core#552]
12 integration tests consistently fail.  We should fix them or delete them.

Example of a failing build: https://travis-ci.org/search/grails-spring-security-core

Failure details:
```
- Running tests for configuration static with GEB: chromeHeadless and Grails 3.3.0
 -- Test there are no roles initially(specs.RoleSpec)
 -- Test add a role(specs.RoleSpec)
specs.RoleSpec > add a role FAILED
    org.openqa.selenium.WebDriverException at RoleSpec.groovy:34
 -- Test edit the details(specs.RoleSpec)
specs.RoleSpec > edit the details FAILED
    geb.error.RequiredPageContentNotPresent at RoleSpec.groovy:45
 -- Test show role(specs.RoleSpec)
specs.RoleSpec > show role FAILED
    geb.error.RequiredPageContentNotPresent at RoleSpec.groovy:76
 -- Test delete role(specs.RoleSpec)
specs.RoleSpec > delete role FAILED
    geb.error.RequiredPageContentNotPresent at RoleSpec.groovy:86
 -- Test there are no users initially(specs.UserSpec)
 -- Test add a user(specs.UserSpec)
specs.UserSpec > add a user FAILED
    org.openqa.selenium.WebDriverException at UserSpec.groovy:34
 -- Test edit the details(specs.UserSpec)
specs.UserSpec > edit the details FAILED
    geb.error.RequiredPageContentNotPresent at UserSpec.groovy:48
 -- Test show user(specs.UserSpec)
specs.UserSpec > show user FAILED
    geb.error.RequiredPageContentNotPresent at UserSpec.groovy:83
 -- Test delete user(specs.UserSpec)
specs.UserSpec > delete user FAILED
    geb.error.RequiredPageContentNotPresent at UserSpec.groovy:93
 -- Test create roles(specs.StaticSecuritySpec)
specs.StaticSecuritySpec > create roles FAILED
    org.openqa.selenium.WebDriverException at StaticSecuritySpec.groovy:29
 -- Test create users(specs.StaticSecuritySpec)
specs.StaticSecuritySpec > create users FAILED
    org.openqa.selenium.WebDriverException at StaticSecuritySpec.groovy:75
 -- Test secured urls not visible without login(specs.StaticSecuritySpec)
 -- Test check allowed for admin1(specs.StaticSecuritySpec)
specs.StaticSecuritySpec > check allowed for admin1 FAILED
    org.openqa.selenium.WebDriverException at StaticSecuritySpec.groovy:172
 -- Test check allowed for admin2(specs.StaticSecuritySpec)
specs.StaticSecuritySpec > check allowed for admin2 FAILED
    org.openqa.selenium.WebDriverException at StaticSecuritySpec.groovy:229
15 tests completed, 12 failed
:functional-test-app:integrationTest FAILED
:functional-test-app:mergeTestReports
```

**Steps to reproduce**

Run the following command in the root of the project:
```
./gradlew -DTESTCONFIG=static -Dgeb.env=chromeHeadless functional-test-app:check
```

**Comment by ddelponte** [comment]
After some investigation, here are my findings I uncovered while testing locally:

Executing the following command in the root of the project (`grails-spring-security-core`) duplicates the errors seen in Travis:
```
./gradlew -DTESTCONFIG=static -Dgeb.env=chromeHeadless functional-test-app:check
```

Executing the following command in the root of the project (`grails-spring-security-core`) will result in all tests passing (assuming you have firefox installed):

```
./gradlew -DTESTCONFIG=static functional-test-app:check
```

The same tests will run and pass if you execute the following command (assuming you have firefox installed) in directory `grails-spring-security-core/functional-test-app`

```
grails -DTESTCONFIG=static test-app -integration
``` 

And this will fail the same as Travis if run in directory `grails-spring-security-core/functional-test-app`:

```
grails -DTESTCONFIG=static -Dgeb.env=chromeHeadless test-app -integration

```

So.... the problem is with `-Dgeb.env=chromeHeadless`.  These tests are failing when run in a headless environment.

I will continue to investigate.

**Comment by ddelponte** [comment]
Problem solved :)

Integration tests failed if run in a `chromeHeadless` environment.

Upgrading the `chromedriver` and `geckodriver` to more recent versions resolved the issue.

I also added some additional code to `build.gradle` that users may comment out if they wish to see more test failure details in Travis.  It helps with troubleshooting.

**Comment by sdelamo** [comment]
Closed by: https://github.com/grails-plugins/grails-spring-security-core/commit/0a5cc69f27ac0cd3810c49826603336b7fa8e9d2

and: 

https://github.com/grails-plugins/grails-spring-security-core/commit/4b859ddf59660b1646990d82d5b93c12d84d8d4d
