### ISSUE TITLE
encode password even when password is not updating

### ISSUE THREAD

**Issue by pangeaos** [grails-plugins/grails-spring-security-core#558]
When I try to update some variables it's encoding again the password. 
I'm trying to update userSettings object but always change the password.

I'm using mongodb as database

Any idea?

**User**

```
@GrailsCompileStatic
@EqualsAndHashCode(includes="username")
@ToString(includes="username", includeNames=true, includePackage=false)
class User implements Serializable {
	ObjectId id
	String password
	String username
	boolean enabled = true
	boolean accountExpired
	boolean accountLocked
	boolean passwordExpired
	Set<Role> authorities
	UserSettings userSettings
	static embedded = ["authorities", "userSettings"]
}
```

**UserSettings**

```
@GrailsCompileStatic
class UserSettings implements Serializable {
	boolean showNickname
	String test
	static constraints = {
		showNickname nullable: true
		test nullable: true
	}
}
```

**Service class**

```
@CompileDynamic
def updateSettings(String username, boolean showNickname, String test){
	def user = findUserByUsername(username)
	if (!user.userSettings) {
		user.userSettings = new UserSettings()
	}
	user.userSettings.showNickname = showNickname
	user.userSettings.test = test
	user.save flush:true
	return user
}
```

### Environment Information

- **Operating System**: OSX
- **Grails Version (if using Grails):** 3.3.2
- **JDK Version:** 1.8.0_131

**Comment by ddelponte** [comment]
@barcelona23 What version of GORM are you using?

There was a bug related to MongoDB `isDirty()` that was fixed in GORM 6.0.11.

The following link provides a workaround as well as more details on the bug:

https://github.com/grails/grails-core/issues/10609

**Comment by barcelona23** [comment]
Hi @ddelponte 

I'm using
grailsVersion=3.3.2
gormVersion=6.1.8.RELEASE
compile "org.grails.plugins:mongodb:6.1.4"
compile "org.grails.plugins:spring-security-core:3.2.0"

Spring core plugin has this Listener

```
@CompileStatic
class UserPasswordEncoderListener extends AbstractPersistenceEventListener {

	@Autowired
	SpringSecurityService springSecurityService

	UserPasswordEncoderListener(final Datastore datastore) {
		super(datastore)
	}

	@Override
	protected void onPersistenceEvent(AbstractPersistenceEvent event) {
		if (event.entityObject instanceof User) {
			User u = (event.entityObject as User)
			if (u.password && (event.eventType == EventType.PreInsert || (event.eventType == EventType.PreUpdate && u.isDirty('password')))) {
				event.getEntityAccess().setProperty("password", encodePassword(u.password))
			}
		}
	}

	@Override
	boolean supportsEventType(Class<? extends ApplicationEvent> eventType) {
		eventType == PreUpdateEvent || eventType == PreInsertEvent
	}

	private String encodePassword(String password) {
		springSecurityService?.passwordEncoder ? springSecurityService.encodePassword(password) : password
	}
}
```

The problem is when I try to update userSettings, because if the userSettings does not exists and I create it, it's working as expected.

**Comment by barcelona23** [comment]
I do not know if it's an issue or what but I did some changes in the services.

Instead of set each attribute and setting the whole object. Now it's working.

Any idea? Bug or bad coding for me?

```
@CompileDynamic
def updateSettings(String username, UserSettings settings){
    def user = findUserByUsername(username)

    if (!user.settings) {
        user.settings = new UserSettings()
    }
    user.settings = settings
    user.save flush:true
    return user
}
```

**Comment by ddelponte** [comment]
Is the following code necessary?:

```
if (!user.settings) {
    user.settings = new UserSettings()
}
```

If you would be so kind as to attach a sample app or link to a github repo that reproduces the issue I'd be happy to dig a little deeper.

**Comment by ddelponte** [comment]
Marking as "Cannot reproduce" and closing.  

I would be happy to reopen this if an application duplicating the problem is attached or linked to.

**Comment by barcelona23** [comment]
Hello @ddelponte,

I'm having same problem again.
I'm trying to update card object into User class. The updating is working as expected but it changes the password again.

Please find attached an app demo.

grailsVersion=3.3.8
grailsWrapperVersion=1.0.0
gormVersion=6.1.10.RELEASE
gradleWrapperVersion=3.5
mongodb

User class
Basically is the default user class but it has a Customer class.

![screen shot 2018-09-26 at 17 29 57](https://user-images.githubusercontent.com/221474/46115007-69e8bd00-c1b2-11e8-9ace-44dae1a878fd.png)

Customer class
![screen shot 2018-09-26 at 17 30 07](https://user-images.githubusercontent.com/221474/46115058-a1576980-c1b2-11e8-82cd-382a928812c1.png)

Card class
![screen shot 2018-09-26 at 17 30 17](https://user-images.githubusercontent.com/221474/46115061-a3212d00-c1b2-11e8-9712-29549fa4cdda.png)

UserService
![screen shot 2018-09-26 at 17 29 38](https://user-images.githubusercontent.com/221474/46115198-25115600-c1b3-11e8-8d9a-b1954d65c6c0.png)



[grailsDemo.zip](https://github.com/grails-plugins/grails-spring-security-core/files/2421898/grailsDemo.zip)

**Comment by ddelponte** [comment]
FYI - I've confirmed the `isDirty()` does not appear to be working as expected.

I recommend filing an issue against the gorm-mongodb repository at https://github.com/grails/gorm-mongodb because the issue is not specific to the `grails-spring-security-core` plugin.

In the meantime, a workaround would be to update the `UserPasswordEncoderListener.onPersistenceEvent()` method to the following:

```
    private void encodePasswordForEvent(AbstractPersistenceEvent event) {
        if (event.entityObject instanceof User) {
            User u = event.entityObject as User
            if (u.password && ((event instanceof PreInsertEvent) || (event instanceof PreUpdateEvent && u.isDirty('password')))) {
                if (u.password && (event.eventType == EventType.PreInsert || (event.eventType == EventType.PreUpdate && u.hasChanged('password')))) {
                    if (event.eventType == EventType.PreUpdate) {
                        User originalUser = User.get(u?.id)
                        if (originalUser.password != u.password) {
                            event.getEntityAccess().setProperty("password", encodePassword(u.password))
                        }
                    } else {
                        event.getEntityAccess().setProperty("password", encodePassword(u.password))
                    }

                }
            }
        }
    }
```

Hope this helps!  Thanks!
