### ISSUE TITLE
Grails updating embedded object, the password is updated too.

### ISSUE THREAD

**Issue by barcelona23** [grails-plugins/grails-spring-security-core#561]
I'm trying to save charges object into a collection, the collection is an embedded object. The update functionality is working as expected. The problem is when I update the password update too.

I'm using the grails spring security plugin. it has a class to encode the password. **UserPasswordEncoderListener**

Using grails 3.3.8, gorm 6.1.10.RELEASE and mongodb.

This is the way that I'm trying to update the collection:

    def user = User.findByUsername("username")
    		def charge = new Charge(
    			amount: "100",
    			description: "some description",
    			user: user
    		)
    		def customer = new Customer(
    			charges: [charge]
    		)
    
    		user.customer = customer
    		user.save flush: true, failOnError:true

Any idea? or what is the best option to save/update embedded objects.?
The documentation says about some methods https://docs.grails.org/latest/ref/Domain%20Classes/addTo.html

I tried without success.

User class

 
    @GrailsCompileStatic
    @EqualsAndHashCode(includes='username')
    @ToString(includes='username', includeNames=true, includePackage=false)
    class User implements Serializable {
    
    	/* MongoDB */
    	ObjectId id
    
    	...

        String username
        String password
    
    	/* Role Users */
    	Set<Role> authorities
    
    	Customer customer
    
    	static embedded = ['authorities', 'customer']
    
    	static mapping = {
    		collection "users"
    		password    column: '`password`'
    	}
    
    	...
    }

Customer class

 

    @GrailsCompileStatic
     class Customer implements Serializable {
        
        	...
        
        	static hasMany = [
        		charges: Charge
        	]
        
        	...
        
        }

Charge Class

    @GrailsCompileStatic
    class Charge implements Serializable {
    
    	ObjectId id
    
    	String amount
    
    	static belongsTo = [ user: User ]
    
    	static mapping = {
    		collection "charges"
    	}
    
    	...
    }

UserPasswordEncoderListener class

    @Override
    	protected void onPersistenceEvent(AbstractPersistenceEvent event) {
    		if (event.entityObject instanceof User) {
    			User u = (event.entityObject as User)
    			if (u.password && (event.eventType == EventType.PreInsert || (event.eventType == EventType.PreUpdate && u.isDirty('password')))) {
    				event.getEntityAccess().setProperty("password", encodePassword(u.password))
    			}
    		}
    	}

**Comment by ddelponte** [comment]
@barcelona23 are you able to provide a sample app which reproduces this issue?

**Comment by ddelponte** [comment]
This appears to be a duplicate of https://github.com/grails-plugins/grails-spring-security-core/issues/558

I will close it if there are no objections.

**Comment by ddelponte** [comment]
FYI - I've confirmed the `isDirty()` does not appear to be working as expected.

I recommend filing an issue against the gorm-mongodb repository at https://github.com/grails/gorm-mongodb because the issue is not specific to the `grails-spring-security-core` plugin.

In the meantime, a workaround would be to update the `UserPasswordEncoderListener.onPersistenceEvent()` method to the following:

```
    private void encodePasswordForEvent(AbstractPersistenceEvent event) {
        if (event.entityObject instanceof User) {
            User u = event.entityObject as User
            if (u.password && ((event instanceof PreInsertEvent) || (event instanceof PreUpdateEvent && u.isDirty('password')))) {
                if (u.password && (event.eventType == EventType.PreInsert || (event.eventType == EventType.PreUpdate && u.hasChanged('password')))) {
                    if (event.eventType == EventType.PreUpdate) {
                        User originalUser = User.get(u?.id)
                        if (originalUser.password != u.password) {
                            event.getEntityAccess().setProperty("password", encodePassword(u.password))
                        }
                    } else {
                        event.getEntityAccess().setProperty("password", encodePassword(u.password))
                    }

                }
            }
        }
    }
```

Hope this helps!  Thanks!
