### ISSUE TITLE
preauthentication with header example/documentation. 

### ISSUE THREAD

**Issue by sfergu** [grails-plugins/grails-spring-security-core#567]
Is the plugin intended to support preauthentication scenarios (like from an http header ala site minder)? If so do you have any pointers to documentation/examples? I posted as you mention on stackoverflow and no one has taken an interest there. I simply want to identify the user from a header and then lookup their roles in the database, but can't seem to find a reference configuration for this scenario. Thanks! If you can give me some pointers I will gladly contribute a reference project for your examples.

**Comment by ddelponte** [comment]
Thanks for reporting this issue @sfergu !
An `EventListener` implementation may be what you're looking for: https://grails-plugins.github.io/grails-spring-security-core/3.2.x/index.html#registeringEventListener

**Comment by ddelponte** [comment]
@sfergu were you able to resolve this issue?

**Comment by sfergu** [comment]
Yes, I finally got it.
