### ISSUE TITLE
RememberMe doesn't work 

### ISSUE THREAD

**Issue by dustindclark** [grails-plugins/grails-spring-security-core#593]
The remember me filter was moved below/after the anonymous filter in [this commit](https://github.com/grails-plugins/grails-spring-security-core/commit/d8757fa1b2298d376813ff8598d0cd84c63037d0#diff-3aba7aae48daea07622627f85134a0c0). This breaks "remember me" because a GrailsAnonymousAuthenticationToken is populated before the remember me filter fires, and remember me processing [is skipped if an authentication token is present](https://github.com/spring-projects/spring-security/blob/5e98b922738a9e272046442692725cb47f5a062a/web/src/main/java/org/springframework/security/web/authentication/rememberme/RememberMeAuthenticationFilter.java#L97).  Also note that the breaking commit is a departure from [Spring's filter order](https://github.com/spring-projects/spring-security/blob/master/config/src/main/java/org/springframework/security/config/http/SecurityFilters.java).

**Comment by bobbywarner** [comment]
@ddelponte Thoughts on this one?  Looks like it's your commit being referenced.  Please let me know.

**Comment by bobbywarner** [comment]
I have now reverted that commit on `3.3.x` and `master`.

**Comment by azavisha-snap** [comment]
@bobbywarner Version 3.3.1 appears to be broken (released before this fix) and two years later there is still no 3.3.2. Can you please release 3.3.2 with this fix? As of right now, the latest of Grails 3 compatible versions (3.3.1) of this plugin doesn't have remember-me, which is a big deal. Thanks!
