### ISSUE TITLE
Documentation Bug: Default is InheritableThreadLocal, but doc states ThreadLocal

### ISSUE THREAD

**Issue by symentis-info** [grails-plugins/grails-spring-security-core#615]
Documentation for 3.3.x and 4.0.0 states in 4.8:
"By default it is stored in a ThreadLocal".
See [Chapter 4.8](https://grails-plugins.github.io/grails-spring-security-core/latest/#securitycontextholder-strategy)

This is not correct. It is in fact InheritableThreadLocal by default.

See (3.3.x):
https://github.com/grails-plugins/grails-spring-security-core/blob/3.3.x/plugin/grails-app/conf/DefaultSecurityConfig.groovy#L346

and (master):

https://github.com/grails-plugins/grails-spring-security-core/blob/master/plugin/grails-app/conf/DefaultSecurityConfig.groovy#L346

I strongly recommend to change the default back to ThreadLocal, as InheritedThreadLocal can lead to strong - and hard to debug - security issues in multi-threaded applications. See #587

**Comment by bobbywarner** [comment]
The docs are now correct as the default has been switched back to ThreadLocal.  Here is the commit that changed it back: https://github.com/grails-plugins/grails-spring-security-core/commit/59e13d8fa07a75d0f648c74b48ca3d3d38229b0f
