### ISSUE TITLE
Modify EventBus ThreadPool to use a DelegatingSecurityContextRunnable  or DelegatingSecurityContextAsyncTaskExecutor

### ISSUE THREAD

**Issue by robertoschwald** [grails-plugins/grails-spring-security-core#619]
As described in #584 , the default MODE_INHERITABLETHREADLOCAL mode can lead to serious security issues when using ThreadPools like the EventBus ThreadPool, as the SecurityContext of once created Threads in the pool are never updated.

To enhance security of the plugin default configuration, one solution could be to use a DelegatingSecurityContextRunnable  or a DelegatingSecurityContextAsyncTaskExecutor.

My recommendation is that the plugin modifies the EventBus ThreadPool if MODE_INHERITABLETHREADLOCAL is active to wrap the runnable in a DelegatingSecurityContextRunnable (optional: allow to use a DelegatingSecurityContextAsyncTaskExecutor instead by config key).

For this, the plugin may detect the used ThreadPool implementation and modify / re-setup accordingly.

See https://github.com/spring-projects/spring-security/issues/6856#issuecomment-518787966

**Comment by bobbywarner** [comment]
The default strategy has now been switched back, so this is no longer an issue.

https://github.com/grails-plugins/grails-spring-security-core/commit/59e13d8fa07a75d0f648c74b48ca3d3d38229b0f
