### ISSUE TITLE
Grails 4 must use POST to exitUserUrl

### ISSUE THREAD

**Issue by mftruso** [grails-plugins/grails-spring-security-core#622]
A dependency in Grails 4 is [upgrading spring security to 5.1.11](https://github.com/mftruso/spring-security-impersonate/blob/master/dependencies.txt#L524). As of 5.1.9, the SwitchUserFilter.exitUserMatcher [defaults to POST](https://github.com/spring-projects/spring-security/issues/4183). The docs and examples for this plugin assume a GET to the exitUserUrl.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Fresh Grails 4.0.4 app with spring security plugin v4.0.2, switchUserFilter enabled
2. login as user `me`
2. switch to user `other`
3. click the `Resume as me` link

### Expected Behaviour

- `GET /logout/impersonate` should still work with the plugin's [Spring Security version](https://github.com/grails-plugins/grails-spring-security-core/blob/v4.0.2/gradle.properties#L5) at `5.1.6.RELEASE`
OR
- upgrade to Spring Security 5.1.9+
- update docs to demonstrate a form POST to the exitUserUrl
- provide plugin configuration to set a custom [SwitchUserFilter.setExitUserMatcher](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/web/authentication/switchuser/SwitchUserFilter.html#setExitUserMatcher-org.springframework.security.web.util.matcher.RequestMatcher-)

### Actual Behaviour

404 Page is displayed. If you use the form POST instead, then you are correctly returned to user `me`

### Environment Information

- **Operating System**: MacOS 10.15.5
- **GORM Version:** 7.0.6
- **Grails Version (if using Grails):** 4.0.4
- **JDK Version:** 1.8

### Example Application

https://github.com/mftruso/spring-security-impersonate

**Comment by dustindclark** [comment]
Would you mind providing an example working config for `exitUserMatcher`? I've tried both of the below configurations and can't get it to work:

```
            switchUser:
                switchFailureUrl: /login/switchAuth?failed=true
                exitUserMatcher: "'/logout/impersonate'"
```

```
            switchUser:
                switchFailureUrl: /login/switchAuth?failed=true
                exitUserMatcher: /logout/impersonate
```

Ends up failing with: `Caused by: org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [java.lang.Boolean] for value '/logout/impersonate'; nested exception is java.lang.IllegalArgumentException: Invalid boolean value '/logout/impersonate'`
