### ISSUE TITLE
Saml2Login support with Grails Spring Security Core

### ISSUE THREAD

**Issue by sandhya0107** [grails-plugins/grails-spring-security-core#634]
I am using Saml2Login(https://docs.spring.io/spring-security/site/docs/current/reference/html5/) in my Grails application along with dependency group: 'org.grails.plugins', name: 'spring-security-core', version: '4.0.3'.

I am able to redirect to IDP without Grails Spring security plugin added in build.gradle along with Saml2Login dependency.
If  i add Grails Spring Security plugin with Saml2Login dependency,  it is redirect to default /login/auth loginform.

Could you please suggest how to support both libraries in my Grails application.

**Comment by bobbywarner** [comment]
GitHub issues is for reporting issues with the plugin.  Please ask usage questions on Stackoverflow or in the Slack channel.
