### ISSUE TITLE
GPSPRINGSECURITYCORE-124: Integrate/provide a way to integrate security into Grails gsp tags

### ISSUE THREAD

**Issue by graemerocher** [grails-plugins/grails-spring-security-core#68]
Original Reporter: bond
Environment: Spring-security-core:1.2.4, Grails: 1.3.7
Version: Not Specified
Migrated From: http://jira.grails.org/browse/GPSPRINGSECURITYCORE-124

Presently, In controller we are using a custom tag-lib which extends SecurityTagLib.

Code inside some controller:
{code}
if(xyz.hasAccess([controller:'role',action:'edit'],'access')){
   g.createLink(controller:'role',action:'edit')
}
{code}

Note: xyz is the custom tag-lib.

If it is possible please inject security in to createLink/resource or any other such tags.

**Comment by burtbeckwith** [comment]
This would require hooks in Grails that the plugin could extend, but there's nothing like that currently.
