### ISSUE TITLE
JDK 17 - Spring Security Core 5.0.0 (Latest) "Failed to compile s2-create-role-hierarchy-entry.groovy"

### ISSUE THREAD

**Issue by codeconsole** [grails-plugins/grails-spring-security-core#767]
### Expected Behavior

Able to run the grails cli

### Actual Behaviour

JDK 17 (61) is not supported by this plugin for no particularly good reason.

Simply adding the plugin to any existing grails project and executing run-app

```
% grails run-app
| Error Failed to compile s2-create-role-hierarchy-entry.groovy: BUG! exception in phase 'semantic analysis' in source unit 's2-create-role-hierarchy-entry.groovy' Unsupported class file major version 61 (Use --stacktrace to see the full trace)
| Error Command [run-app] error: Cannot invoke "org.grails.cli.profile.commands.script.GroovyScriptCommand.setProfile(org.grails.cli.profile.Profile)" because "data" is null (Use --stacktrace to see the full trace)
```

### Steps To Reproduce

grails create-app exampleapp

```
    implementation "org.grails.plugins:spring-security-core:5.0.0" 
```

### Version

5.0.0

**Comment by codeconsole** [comment]
https://github.com/grails-plugins/grails-spring-security-ui/issues/127

**Comment by codeconsole** [comment]
Example App: https://github.com/codeconsole/grails4bugs

**Comment by abrahaj** [comment]
Commenting for more attention to the issue! Another user.

**Comment by codeconsole** [comment]
@abrahaj seems to be working find now with grails 5.2.3 
https://github.com/codeconsole/grails4bugs
