### ISSUE TITLE
GPSPRINGSECURITYCORE-193: Spring security core invalidates session and attempts to access to an attribute after that

### ISSUE THREAD

**Issue by graemerocher** [grails-plugins/grails-spring-security-core#88]
Original Reporter: whitenexx
Environment: Not Specified
Version: Not Specified
Migrated From: http://jira.grails.org/browse/GPSPRINGSECURITYCORE-193

It looks like Spring security core is invalidating the session and then attempting to remove or access an attribute from it after logging out with LogoutController.

When using grails database session plugin from Robert Fischer you can't logout anymore because InvalidatedSessionException is thrown. ( http://stackoverflow.com/questions/12244629/invalidatedsessionexception-in-grails-2-1-with-database-session-1-2-0-and-spring and https://github.com/RobertFischer/grails-database-session )

So anyone who is using heroku isn't able to use spring security core anymore, because you need the database session plugin.

**Comment by burtbeckwith** [comment]
Closing, no response from submitter
