### ISSUE TITLE
Wrong version of spring-security-core is resolved

### ISSUE THREAD

**Issue by matrei** [grails-plugins/grails-spring-security-core#882]
### Expected Behavior

`org.springframework.security:spring-security-core:5.8.1` should be resolved when using plugin version 5.2.0

### Actual Behaviour

`org.springframework.security:spring-security-core:5.7.4` is resolved.

### Steps To Reproduce

``` bash
./gradlew examples-functional-test-app:dependencyInsight --singlepath --dependency "org.springframework.security:spring-security-core" --configuration productionRuntimeClasspath

> Task :examples-functional-test-app:dependencyInsight
org.springframework.security:spring-security-core:5.7.4 (selected by rule)
  Variant runtimeElements:
    | Attribute Name                 | Provided     | Requested    |
    |--------------------------------|--------------|--------------|
    | org.gradle.category            | library      |              |
    | org.gradle.jvm.version         | 8            |              |
    | org.gradle.status              | release      |              |
    | org.gradle.dependency.bundling | external     | external     |
    | org.gradle.libraryelements     | jar          | jar          |
    | org.gradle.usage               | java-runtime | java-runtime |

org.springframework.security:spring-security-core:5.7.4
\--- org.springframework.security:spring-security-web:5.7.4
     \--- project :spring-security-core (requested org.springframework.security:spring-security-web:5.8.1)
          \--- productionRuntimeClasspath

org.springframework.security:spring-security-core:5.8.1 -> 5.7.4
\--- project :spring-security-core
     \--- productionRuntimeClasspath

```

### Environment Information

Ubuntu 2022.04
Java 8

### Example Application

[https://github.com/matrei/grails-security-plugin-issue882](https://github.com/matrei/grails-security-plugin-issue882)

### Version

5.2.5

**Comment by jchharris** [comment]
It resolves properly for me:
```
|    +--- org.grails.plugins:spring-security-core:5.2.0
|    |    +--- org.springframework.security:spring-security-core:5.8.1
|    |    |    +--- org.springframework.security:spring-security-crypto:5.8.1
|    |    |    +--- org.springframework:spring-aop:5.3.24 -> 5.3.23 (*)
```

Where is it getting version 5.7.4 from?  Spring Boot? Check the version of spring boot you are bringing in as that may set the version of Spring Security.

**Comment by matrei** [comment]
Hi @jchharris ,

when doing a dependency check on the Grails Spring Security Plugin project itself, the version of `org.springframework.security:spring-security-core` specified in `gradle.properties` (**5.8.1**) is resolved correctly.

When using the Grails Spring Security Plugin 5.2.0 in Grails 5.2.5 (latest version as of right now), version **5.7.4** of `org.springframework.security:spring-security-core` is resolved.

```bash
org.springframework.security:spring-security-core:5.7.4
\--- org.springframework.security:spring-security-web:5.7.4
     \--- org.grails.plugins:spring-security-core:5.2.0 (requested org.springframework.security:spring-security-web:5.8.1)
```

I am not to familiar with how to interpret all this transitive dependency business but I thought it was odd. Maybe it is expected behavior? I have created [a stock Grails 5.2.5 repo with the security plugin added](https://github.com/matrei/grails-security-plugin-issue882) that shows the problem.

**Comment by jchharris** [comment]
@Matrei I believe what is happening is that Grails 5.2.5 brings in Spring Boot 2.7.5 and if you look at the dependencies in this file:
https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.7.5/spring-boot-dependencies-2.7.5.pom

You will see it sets `<spring-security.version>5.7.4</spring-security.version>`.

The reason it resolves in my project is that I have manually overridden the versions provided by Grails/SpringBoot.  Our security team gets upset if we have vulnerable dependencies so I can't wait for Grails to update to latest versions.

**Comment by matrei** [comment]
@jchharris Ok, thanks for the explanation. Then this is expected behavior, so I'll close this issue.

For anyone coming to this issue looking for answers one way of upgrading the version of this transitive dependency is to set:

```groovy
// build.gradle
ext['spring-security.version'] = '5.8.1'
dependencies {
...
}
```
