### ISSUE TITLE
s2-quickstart version 6.1.0 fails because there is no grails-app/conf/spring directory

### ISSUE THREAD

**Issue by monetschemist** [grails-plugins/grails-spring-security-core#970]
### Expected Behavior

After updating `build.gradle` with

`implementation 'org.grails.plugins:spring-security-core:6.1.0'`

running

` ./gradlew runCommand -Pargs="s2-quickstart org.myorg.myapp User Role"`

should run to completion, creating the appropriate artefacts.

### Actual Behaviour

Instead, s2-quickstart fails with the following message:

    | Error Command execution error: grails-app/conf/spring/resources.groovy (No such file or directory)

**Workaround**

I have found that if I create a fresh application directory:

`grails create-app org.myorg.myapp`

then add the Spring security configuration line shown above into `build.gradle`

then issue a

`mkdir grails-app/conf/spring`

that the subsequent

`./gradlew runCommand -Pargs="s2-quickstart org.myorg.myapp User Role"`

succeeds.  However, if I try creating this directory once the gradle build has failed, further errors occur.

There is probably a "clean" step in the s2-quickstart script somewhere that could be used to sort out the mess in order not to have to create a new app directory.

### Steps To Reproduce

Update `build.gradle` as above and run `s2-quickstart` as above.

### Environment Information

Ubuntu 23.10, latest SDKMAN installed

```
sdk use java 11.0.21-tem
sdk use groovy 3.0.11
sdk use grails 6.1.0
```

### Version

6.1.0

**Comment by monetschemist** [comment]
Just to update the above, the same holds true with Grails 6.1.2 and Spring Security Core 6.1.1.

**Comment by jamesfredley** [comment]
Grails 6.2.1+ generate `grails-app/conf/spring/resources.groovy` from grails-forge cli and start.grails.org.
