### ISSUE TITLE
Grails 6 applications don't generate resources.groovy

### ISSUE THREAD

**Issue by sdelamo** [grails-plugins/grails-spring-security-core#972]
### Issue description

An` grails-app/conf/spring/resources.groovy` with contents: 

```groovy
// Place your Spring DSL code here
beans = {
}
``` 

is necessary for the `s2-quickstart` command to work. However, Grails 6.1 no longer generate such a file.

**Comment by puneetbehl** [comment]
I believe we should update the security plugin to work properly instead of having an empty resources.groovy file.

**Comment by jamesfredley** [comment]
Grails 6.2.1+ generate `grails-app/conf/spring/resources.groovy` from grails-forge cli and start.grails.org.
