### ISSUE TITLE
GPSPRINGSECURITYCORE-206: Support securing controllers/actions/uri's by HTTP method type

### ISSUE THREAD

**Issue by graemerocher** [grails-plugins/grails-spring-security-core#99]
Original Reporter: aasukisuki
Environment: Not Specified
Version: Not Specified
Migrated From: http://jira.grails.org/browse/GPSPRINGSECURITYCORE-206

Add support to secure uri's/controllers/actions by HTTP Method type. This is to allow for secured/unsecured REST transactions. This would also include toggling specific authentication types for specified URLS (ex: Basic authentication for myapp/api/** but no authenication for myapp/api/session POST).

**Comment by alvarosanchez** [comment]
Already fixed by 2ff94e71c6d316ec61999a406513b50eb8552fe6
